### ISSUE TITLE
swg4-AllergyIntolerance codeのslicingの振り分けが同じ値を示している

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#106]
### 概要
path=system, type=valueでsliceを設定しているが、systemは全てJFAGYのURLを指し示しているため振り分けがされないのでは。
※私もSliceについて詳しくないのでまちがった指摘かもしれません。

### 依頼先
SWG4

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/feature/swg5-fix_medication_request_authoredon/StructureDefinition-jp-allergyintolerance.html

### 原因
振り分けルールがあまり適切ではないと思われます。

### 修正案
思い付く案になります。

1)Sliceをそもそも使わない。
JFAGYの中ですべてに禁忌情報が定義されるのであれば、あえてSlicingはしなくても良いのではないでしょうか？
slicingにより、必須入力等の制御もしていないので。

ちなみにau baseはとてもシンプルな構成でした。
http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-allergyintolerance.html

2)Sliceの振り分けルールを見直す。
JFAGYのコード体系が決まっているようであれば
type = #pattern, path=code
にして、コード体系による振り分けができると思います。
ValueSetを元に分けるのは、今の仕組み上で難しそうです。

3)Slicingではなく、派生を利用する。
SWG2の分け方と同様に、派生先で、CodeとCategeoryに対してonlyを利用し利用方法を分ける。

**Comment by ykawazoe** [comment]
.codeにsliceを行わない仕様に変更しました。具体的には、.codeのVSは１つとし、VS中に3つのCS（JFAGY食品、JFAGY医薬品、JFAGY非食品・非食品医薬品）をインクルードするようにしました。

**Comment by findex-miyakawa** [comment]
確認しました。
Code体系を見れば対象のアレルギーがわかるので問題ないかと思います。

CodeSystemを分けたので、systemによるSlicingも可能になっていますが、Slicingの結果で定義が変わることころもないので、そのままで良いと思います。
