### ISSUE TITLE
SWG5-MedicationAdministration サンプルインスタンスにrateRatioを追加するとビルドエラーが発生する

### ISSUE THREAD

**Issue by yoshinori-kodama** [jami-fhir-jp-wg/jp-core-v1x#118]
### 概要
注射実施のサンプルインスタンスに点滴速度 `dosage.rateRatio` を追加したい。
https://github.com/jami-fhir-jp-wg/jp-core-v1x/blob/43da131f38eea4306fa78cc080e5091aae3164bb/input/fsh/examples/JP_MedicationAdministration_Injection_Example.fsh#L82-L83

しかし、↑のコメントを解除してsushiを実行すると、以下のエラーが発生する。
`dosage.rateRatio.numerator` と `dosage.rateRatio.denominator` の要素が見つからないと言われている。
```
Sushi: error The element or path you referenced does not exist: dosage.rateRatio.numerator (00:30.0408)
Sushi: File: /Users/yoshinori.kodama/service/jp-core-v1x/input/fsh/examples/JP_MedicationAdministration_Injection_Example.fsh (00:30.0410)
Sushi: Line: 82                                                                  (00:30.0411)
Sushi: error The element or path you referenced does not exist: dosage.rateRatio.denominator (00:30.0412)
Sushi: File: /Users/yoshinori.kodama/service/jp-core-v1x/input/fsh/examples/JP_MedicationAdministration_Injection_Example.fsh (00:30.0413)
Sushi: Line: 83                                                                  (00:30.0414)
```
profile の `dosage.rate[x]` に付加している extension（投与速度コメント） をコメントアウトすれば、エラーは出なくなる。
↓以下の箇所をコメントアウトする
https://github.com/jami-fhir-jp-wg/jp-core-v1x/blob/2f528aabfb820cc60c92ca8092887d0b3b0331f9/input/fsh/profiles/JP_MedicationAdministration_Injection.fsh#L18

https://github.com/jami-fhir-jp-wg/jp-core-v1x/blob/2f528aabfb820cc60c92ca8092887d0b3b0331f9/input/fsh/profiles/JP_MedicationAdministration_Injection.fsh#L53-L57

- `[x]` の choice 要素があるものに対しての extension がダメなのか...？
- しかし、試しに MedicationRequest の `substitution.allowed[x]` に extension を付けてみたが、サンプルインスタンスに `allowedCodeableConcept` を正しく出力することができた。
- sushi本家のissueにも、ピンポイントなissueはなさそう？ => https://github.com/FHIR/sushi/issues

### 依頼先
- TBD

**Comment by yoshinori-kodama** [comment]
sushi を git clone して、ログを仕込んでデバッグしてみたところ、ここで例外がスローされている。
https://github.com/FHIR/sushi/blob/d785865cf9d84e89316b0abec9ff2c9671fd5871/src/fhirtypes/StructureDefinition.ts#L531

```typescript
if (
  !currentElement ||
  currentElement.max === '0' ||
  (arrayIndex != null &&
    currentElement.max !== '*' &&
    (arrayIndex >= parseInt(currentElement.max) || currentElement.max === '1'))
) {
  // We throw an error if the currentElement doesn't exist, has been zeroed out,
  // or is being incorrectly accessed as an array
  throw new CannotResolvePathError(path);
}
```

**Comment by yoshinori-kodama** [comment]
`this.type` には Ratio と Quantity が入ってくるため、`this.type?.length === 1` の条件を満たさない（length = 2 になる）
https://github.com/FHIR/sushi/blob/86cc90d3e85068f3c23e581b5fb3ae54997f386c/src/fhirtypes/ElementDefinition.ts#L2219-L2221
```typescript
const proceedToUnfold =
  (this.type?.length === 1 && (!isChoiceElement || (this.type[0].profile ?? []).length <= 1)) ||
  this.contentReference;
```
proceedToUnfold は `undefined` となるため、以下のIfに入らない。
https://github.com/FHIR/sushi/blob/86cc90d3e85068f3c23e581b5fb3ae54997f386c/src/fhirtypes/ElementDefinition.ts#L2222

そうすると、`MedicationAdministration.dosage.rate[x]` の子要素（numeratorなど）が展開されず、パスが存在しない状態で Instance の作成処理に入るため、`error The element or path you referenced does not exist: dosage.rateRatio.numerator` が発生する。

JP-Coreでは `rateRatio` しか使用しない予定なので、`* dosage.rate[x] only Ratio or SimpleQuantity` を `* dosage.rate[x] only Ratio` に変更して、`this.type?.length === 1` の条件を満たすようにすればよさそう。

これだとだめ
```
* dosage.rate[x].extension contains JP_MedicationAdministration_DosageRate_RateComment named RateComment 0..*
* dosage.rate[x] only Ratio
* dosage.rate[x].extension ^slicing.discriminator.type = #value
* dosage.rate[x].extension ^slicing.discriminator.path = "url"
* dosage.rate[x].extension ^slicing.rules = #open
* dosage.rate[x].extension[RateComment] only JP_MedicationAdministration_DosageRate_RateComment
* dosage.rate[x].extension[RateComment] ^sliceName = "RateComment"
```
これなら通る（ `* dosage.rate[x] only Ratio` の記述順序を入れ替え）
```
* dosage.rate[x] only Ratio
* dosage.rate[x].extension contains JP_MedicationAdministration_DosageRate_RateComment named RateComment 0..*
* dosage.rate[x].extension ^slicing.discriminator.type = #value
* dosage.rate[x].extension ^slicing.discriminator.path = "url"
* dosage.rate[x].extension ^slicing.rules = #open
* dosage.rate[x].extension[RateComment] only JP_MedicationAdministration_DosageRate_RateComment
* dosage.rate[x].extension[RateComment] ^sliceName = "RateComment"
```

**Comment by yoshinori-kodama** [comment]
大江先生
コメントありがとうございます。
なるほど、リファレンスにそのような記述が...

こちらこそ、大変勉強になりました。

**Comment by skoba** [comment]
ProfileでRatio or SimpleQuantityに制約する意義がないため，該当部分を削除してどちらのインスタンスもビルドが通るようにした。
