### ISSUE TITLE
SWG4-全般 注意事項、参考文献等に未定の語句が残っている

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#127]
### 概要
参考文献等に未定の語句が残っている。

### 依頼先
SWG4

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/release/JPCore_V1.1/StructureDefinition-jp-condition.html
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/release/JPCore_V1.1/StructureDefinition-jp-allergyintolerance.html
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/release/JPCore_V1.1/StructureDefinition-jp-procedure.html

### 修正しないとどう困るか
利用する側からクレームが来る可能性あり

**Comment by ykawazoe** [comment]
「未定」を適宜修正しました。
