### ISSUE TITLE
SWG4 CarePlanの説明

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#128]
### 概要
intro-notesの説明がない

### 依頼先
SWG4

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/release/JPCore_V1.1/StructureDefinition-jp-careplan.html

v1.1に入れるのであれば説明書きを記載をお願いします。

**Comment by ykawazoe** [comment]
検討不十分のため、v1.1には入れないつもりです。

**Comment by findex-miyakawa** [comment]
マイルストーンを1.2に付けなおしました。

**Comment by findex-miyakawa** [comment]
1.2に入れているので、本IssueとしてはCloseとします。
