### ISSUE TITLE
長いサンプルインスタンスの折りたたみ方

### ISSUE THREAD

**Issue by skoba** [jami-fhir-jp-wg/jp-core-v1x#131]
### 概要

サンプルインスタンスで長いものについては折りたたんで表示することがSimplifierではできたが、Sushiでは表示されなくなるので長いままにしてしまっている。

### 依頼先
不明

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-medicationrequest-injection.html

### 期日

特になし

### 要望背景

　注射など複数の薬剤を含むサンプルはどうしても長くなる。全体を表示するのが望ましいが全体としての見通しが悪くなるため、必要ならば展開できるように折りたたみができたほうがいい。

### 修正案

Sushiの仕様かもしれませんが、JSONサンプルを折りたためる方法があればそれを利用したいです。

**Comment by yoshinori-kodama** [comment]
### MarkDownの記法
![スクリーンショット 2022-07-15 19 03 02](https://user-images.githubusercontent.com/41604968/179201746-ad55c0c9-ca79-42d5-9214-c861113a2ebf.png)

### Github issues
<details>
<summary><b>FHIRでの処方例一部抜粋(クリックで展開)</b></summary>
<div>

```json
{
    "resource": {
        "resourceType": "MedicationRequest",
        "identifier": [{
                "system": "http://sample.com/medication",
                "value": "1234567890.1.1"
// (省略)
```
</div>
</details>

### Simplifier
Githubと同様に展開可能
![スクリーンショット 2022-07-15 18 55 39](https://user-images.githubusercontent.com/41604968/179201985-242c6ca4-85d6-4ac5-8672-04dde90e1185.png)

### IG-Publisherでビルドされた実装ガイド
プレーンテキストになってしまっている
![スクリーンショット 2022-07-15 18 55 54](https://user-images.githubusercontent.com/41604968/179202061-619b32a5-7928-479e-ab9e-e8709f50e7b9.png)

**Comment by yoshinori-kodama** [comment]
コードブロックをやめて、html の `<pre>`タグと`<code>`タグを使用すると、展開後も改行、インデントが残ったまま表示された。（ただし、jsonのシンタックスハイライトは難しそう）

### markdown
```
<details>
<summary><b>FHIRでの処方例一部抜粋(クリックで展開)</b></summary>
<pre>
<code>
{
    "resource": {
        "resourceType": "MedicationRequest",
        "identifier": [{
                "system": "http://sample.com/medication",
                "value": "1234567890.1.1"
// (省略)
</code>
</pre>
</details>
```

### IG-Publisherでビルドされた実装ガイド
<img width="1133" alt="スクリーンショット 2022-07-21 13 17 38" src="https://user-images.githubusercontent.com/41604968/180129041-8d4c2b82-6d06-4bfa-b0af-62765e000442.png">

**Comment by yoshinori-kodama** [comment]
## plan.2
jekyllでは `highlight` タグを用いることで、シンタックスハイライトが実現できるらしい。 
https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting

### markdown
```
<details>
<summary><b>FHIRでの処方例一部抜粋(クリックで展開)</b></summary>
<dev>

{% highlight json %}
{
    "resource": {
        "resourceType": "MedicationRequest",
        "identifier": [{
                "system": "http://sample.com/medication",
                "value": "1234567890.1.1"
// (省略)
{% endhighlight %}
</dev>
</details>
```

### Github Issues（効かない）
<details>
<summary><b>FHIRでの処方例一部抜粋(クリックで展開)</b></summary>
<dev>

{% highlight json %}
{
    "resource": {
        "resourceType": "MedicationRequest",
        "identifier": [{
                "system": "http://sample.com/medication",
                "value": "1234567890.1.1"
// (省略)
{% endhighlight %}
</dev>
</details>

### IG-Publisherでビルドされた実装ガイド
![スクリーンショット 2022-07-22 21 11 36](https://user-images.githubusercontent.com/41604968/180436729-8207e03f-49c6-4a0c-b8cd-a0ebc6f09bab.png)

**Comment by findex-miyakawa** [comment]
本件、closeで良いのではないでしょうか？

**Comment by findex-miyakawa** [comment]
#372 にてリンク形式置き換えました。
