### ISSUE TITLE
swg2-JP Core DiagnosticReportの派生

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#141]
### 概要
JP Core DiagnosticReportをLabResultとRadiologyに分けていますが、fshファイルにてコメントを除くと、違いはeffectiveTimeの指定の違いぐらいしかありません。
CategoryやCodeについてそれぞれにValueSetを作成し、only 句等でわけるのが適切と思いますがいかがでしょうか？

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-diagnosticreport-radiology.html
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-diagnosticreport-labresult.html

**Comment by kis-hirayama** [comment]
ユースケース毎にわける
