### ISSUE TITLE
swg2-Observation Labresultのcategoryやcodeに対するvalueSetを作るべきでは

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#149]
### 概要
Labresultについてのfshファイル上ではコメント定義がほとんどになっている。
commonより派生を行っているので、CategoryやCodeについて、ValueSetによる絞り込みや(exactly)指定による値の固定等を使って差別化をすべきでは。

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/release/JPCore_V1.1/StructureDefinition-jp-observation-labresult.html

**Comment by findex-miyakawa** [comment]
Catagoryは下記に限定
http://hl7.org/fhir/R4/codesystem-observation-category#laboratory

Codeは「JLAC10」の指定する

とするのではいかがでしょうか。

**Comment by kis-hirayama** [comment]
Category、Codeは問題ない
