### ISSUE TITLE
swg2 terminologyServerの定義の確認

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#150]
### 概要
Aliasにて下記のTerminalServerでの定義がありますが、これらはすでにコードの定義がされているのでしょうか？
TerminalServerのアクセス方法がよくわかっておらず、既に定義済みの用でしたら取り下げます。

Alias: $labResult-code = http://jpfhir.jp/fhir/Common/ValueSet/labResult-code
Alias: $bodyMeasurement-category = http://jpfhir.jp/fhir/Common/ValueSet/bodyMeasurement-category
Alias: $bodyMeasurement-code = http://jpfhir.jp/fhir/Common/ValueSet/bodyMeasurement-code
Alias: $observation-bodySite = http://jpfhir.jp/fhir/Common/ValueSet/observation-bodySite
Alias: $observation-method = http://jpfhir.jp/fhir/Common/ValueSet/observation-method
Alias: $socialHistory-code = http://jpfhir.jp/fhir/Common/ValueSet/socialHistory-code
Alias: $vitalSigns-category = http://jpfhir.jp/fhir/Common/ValueSet/vitalSigns-category
Alias: $vitalSigns-code = http://jpfhir.jp/fhir/Common/ValueSet/vitalSigns-code

### 依頼先
SWG2

**Comment by kis-hirayama** [comment]
担当：平山

**Comment by findex-miyakawa** [comment]
別Issueに分けたので本Issueは終了します。
