### ISSUE TITLE
swg5 内服・概要の投与経路のCodeSystemの値が処方情報HL7FHIR記述仕様と異なっている

### ISSUE THREAD

**Issue by tmskmr** [jami-fhir-jp-wg/jp-core-v1x#160]
### 概要
JP MedicationRequestプロファイルの投与経路のCodeSystemの値が現状「http://terminology.hl7.org/CodeSystem/v2-0162」となっているが、
処方情報HL7FHIR記述仕様では「http://jpfhir.jp/fhir/ePrescription/CodeSystem/route-codes」となっており、異なっている

### 依頼先
SWG5

### 該当ページ
StructureDefinition-jp-medicationrequest-notes.md

### 修正しないとどう困るか
JP Coreと処方情報HL7FHIR記述仕様とで仕様が食い違ってしまう

### 原因
不明

### 修正案
1. 処方情報HL7FHIR記述仕様に合わせる
2. JP CoreでのTerminology Bindingは「preferred」であるので、個別仕様での仕様変更としてそのままにする

**Comment by skoba** [comment]
JP Coreと処方情報は一部異なっております(canonical URLなど）が、いずれはcoreを元に処方情報記述仕様を書き直すことになっております。
これはそのままにさせてください。
