### ISSUE TITLE
swg2-Observation VitalSingsのCategory

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#161]
### 概要
Observation.VitalSings CategoryのTerminologyを新たに設定していますが、

FHIR Baseで指定されているTerminology
http://terminology.hl7.org/CodeSystem/observation-category#vital-signs
のコードが存在しているので、こちらを利用するで良いと思いますが、いかがでしょうか？

### 依頼先
swg2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-observation-vitalsigns.html

**Comment by kis-hirayama** [comment]
Slackで回答済み
