### ISSUE TITLE
swg4 Terminologyの説明にて日本語と英語が混在する。

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#181]
### 概要
Terminologyの説明にて日本語と英語が混在しています。
日本語の記載に統一するようにお願いします。

### 依頼先
SWG4

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/artifacts.html#terminology-code-systems

**Comment by ykawazoe** [comment]
[develop 8389948] Descriptionを日本語に統一しました。

**Comment by findex-miyakawa** [comment]
修正ありがとうございました。
