### ISSUE TITLE
swg5 MedicationRequest, MedicationDispense, MedicationAdministration一意キーの生成ルール

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#182]
### 概要
薬剤関連にて、オーダ番号、RP番号、薬剤表示順の３つのIdentifier型がSliceによって定義されている。
rp番号や薬剤表示順は単独の一意性は無く、これら３つを組み合わせたものIdentifierとして定義すべきではないでしょうか？

※文献上、このような使い方が良いかどうかというのを判断できるページはないので、質問になります。

PatientのIdentifierでは、ローカルの患者ID、MyNuberのID、地域連携患者ID等の発行主体毎に一意性が確保されているものが設定されているとの認識です。

### 依頼先
SWG5

### 該当ページ
medication request関連

### 修正案

Coverageの被保険者証の番号について考慮したときは下記のように定義をしてみました。
※まだPull Request中です。

- Identifierに対してextensionとして、被保険者（記号、番号、枝番）をそれぞれ定義
- cadinalityについては1 Identifierについてはそれぞれ　(0 or 1) ..1 にて定義
- valueについてはこれらの文字列を結合したもの定義
- 
https://github.com/jami-fhir-jp-wg/jp-core-v1x/pull/175
[https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/feature/swg3-coverageindenti[…]C%E4%BD%9C%E6%88%90/StructureDefinition-jp-coverage.html](https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/feature/swg3-coverageindentifier%E8%A2%AB%E4%BF%9D%E9%99%BA%E8%80%85%E3%82%AD%E3%83%BC%E4%BD%9C%E6%88%90/StructureDefinition-jp-coverage.html)

**Comment by skoba** [comment]
IDを組み合わせるというのは、例えばオーダ番号1, Rp番号2, 表示順3であれば、ID: 1-2-3のような形で表現すべきと言うことでしょうか？

**Comment by findex-miyakawa** [comment]
はい。そのように考えています。

**Comment by skoba** [comment]
IDそれぞれが意味があるので、それを組み合わせてデータを作ってしまうと後で意味を分解しようとしたときにParserを作る必要が出てきます。データの正規化という意味でも好ましい選択ではありません。
オーダー -* Rp -* 薬剤 というようなE-R関連があって、1つのオーダーに複数のRp、一つのRpに複数の薬剤が関連付けられるのであれば、オーダー、Rp、薬剤にそれぞれID割り振ればいいのですけどもMedicationRequestは違います。
内服、外用薬剤ではBundle -* MedicationRequest - 薬剤 です。MedicationRequestがBundle内で繰り返されるだけで、オーダー、Rp、表示順を表現しないといけません。BundleにオーダーIDを格納するように取り決めることもできますが、MedicationRequest単体で使われることも意識するとオーダーIDを記入できるようにした方がいいです。 （編集済み） 
[14:38](https://hl7fhir-jp-wg.slack.com/archives/CLS6U6RQR/p1659073128080569)
薬剤の表示順については議論がありましたが、紙で表現できることは電子的にも表現できた方がいいだろうという大江先生の意見を元に表示順を示すことになりました。XMLであれば、表示順はあえて明示する必要もありませんけども、JSONでは明示する必要があります。RP番号と表示順を格納するところがIdentifierしかないのでスライス切って定義することにしました。
[14:39](https://hl7fhir-jp-wg.slack.com/archives/CLS6U6RQR/p1659073189612259)
たとえば、RpNumberやdisplayOrderというextensionをつけて表現することも可能かとは思いますが、構造的にも意味的にも大差はなく好みの問題かなとも思います。

**Comment by skoba** [comment]
変更の影響が大きいと考えられるため、R4.6以降に対応するときに検討することとします。

**Comment by HERMITRION** [comment]
横からで失礼します。SWG2 田中@岩手医大です。
SWG2でServiceRequestを検討しています。

話題になっているオーダ番号は他の検査でも同様に利用されるもので、ServiceRequestにも格納されることを想定していますが、同時に関連する一連のリソースにidentifierとして持っていただくことは自然であろうと思っています。

例えば放射線画像検査ではDICOMを取り扱うImagingStudyとDICOM以外の画像を取り扱うMediaあるいはDocumentReference、レポートを取り扱うDiagnosticReport、使用薬剤に関連するMedicationStatementなどに同じオーダ番号が格納されることが想定されると思います。
一方で、ImagingStudyではidentifierには基本的にはDICOMを取り扱うリソースであるため、DICOMのStudy Instance UIDなどが格納されることが本家で決められており、DICOMに紐づくことが第一に決められていますが、ここにオーダ番号を「一意に設定する」ことは難しく、複数持つことができるidentifierの一つとしてオーダ番号が収められることが想定されます。

キーが分かれていてもシステムで判別して取り出せば済む話かと愚考した次第です。

このあたりの取り扱いは特定の領域に限定される話ではないと思いますので、今後の全体での検討が必要に思います。

**Comment by findex-miyakawa** [comment]
FHIRの仕様に反しない限りで、有効な利用な方法があるのであれば良いのですが、JP Coreとしては派生される側の模範にならなければならないという意味もあるので、違反したりトリッキーな使い方にならないように気を付けるべきだと考えています。

FHIR仕様を想像するに、オーダー情報はbased-onカラムに格納されているServiceRequestを辿り入手するというのを想定しているようです。subjectで患者IDを辿るのと同様です。

各リソース毎のIdentifierについて、そのリソース毎の識別子を入れるというルールになっているのと、複合インデックス的な使い方ができるかを探しているのですが今のところ見つかっておりません。

文字列結合もあまりよくないのは理解しているのですが、それより良い策が見当たらないというのが現状です。
引き続き、何か良い方法がないかをしらべるようにします。

**Comment by tmitanitky** [comment]
宮川さんの「違反したりトリッキーな使い方にならないように気を付けるべき」という考え方に大いに賛成します。そのような倹約的な方針の方が、本家のバージョンアップに追随する際にも問題が少ないだろうと思います。

MedicationRequestを見てみるとMedicationRequest.groupIdentifierというエレメントがあり、いわゆるオーダ番号は本来こちらに該当するように思います。Rp番号も複数の薬剤にcommonなので同じくgroupIdentifierで良い気はしますが、groupIdentifierはどういう意図が0..1なので置き場がないですね…。

考えてみると、薬剤表示順のみは一意性があり、単にnamespaceが極めて狭い（各RPごとのnamespace）だけでIdentifierとしては適格だと思います。ただ、その場合も他のRPと同じIdentifier.systemを共有するとnamespaceが混ざってしまうので、Identifier.typeを指定する方が良さそうです。

以上から、問題は完全には解決しないものの、Rp番号はidentifierに残して、オーダー番号をgroupIdentifierに移すというのはありうるオプションと思います。

また、やや大改造にはなりますが、RequestGroupリソースを用いることで階層構造を持つことができ、RequestGroup.action内のRequestGroup（RP）の順、MedicationRequestの順で、自然にRp番号と薬剤表示順の情報をもたせることができます。Identifier周りを重視するなら、こちらの方針もありうるかもしれません。

**Comment by HERMITRION** [comment]
「違反したりトリッキーな使い方にならないように気を付けるべき」という考え方は私も大賛成です。

ただ、identifierに「Rpを設定するか」という観点からは私は異なる意見を持っています。
Rpはあくまでも用法に依存するグループで一つの処方内での一意性はありますが、情報システム全体においての一意性は担保されません。そのために宮川さんは組み合わせを提案されたと理解しています。
すべての検査や処方がオーダを前提に実施されるという建付けで考えるのであれば、ServiceRequestを検討する立場から話をすると、オーダ番号が主キーとなる必要があり、その意味ではidentifierにはオーダ番号の方を優先的に残す方が良いかと思います。

Identifier.typeを有効活用する点は私も賛成で、medicationではわざわざidentifier.idをstringで設定していますが、identifier.type.textでstringが使えますのでそちらを利用しない理由がわからないというのが正直なところです。swg5ですでに議論されたところでもあろうかと思いましたので、あえて先の投稿では書きませんでしたが、システム全体での利用を考慮した時にはidentifierの取り扱いは全体で意識合わせする必要性が出てくると思っております。
