### ISSUE TITLE
swg3 Patient.nameに関する記述

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#192]
### 概要

Patient.name ^commentの記述に下記があるが、
「漢字、カナの指定がない場合やローマ字名の場合などはデフォルトスライスが適用される。」
変更により、定義がSliceはりようされなくなったので、記述に合わせる必要がある。

### 依頼先
SWG3

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/release/JPCore_V1.1/StructureDefinition-jp-patient-definitions.html

### 修正案
【現行】
・漢字氏名・漢字、カナの指定がない場合やローマ字名の場合などはデフォルトスライスが適用される。

【修正案】
上記の記述を削除。

**Comment by Shunsuke-Doi** [comment]
SWG3上中さんが対応しました。
