### ISSUE TITLE
swg2 DiagnosticReport-RagiologyのMustSupport定義

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#193]
### 概要
DiagnosticReport-RagiologyのMustSupport定義がリソース上はMustSupportがないが、IGの-notesの説明にMustSupportの記述が残っている。

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-diagnosticreport-radiology.html

### 修正案
IG側の記述を削除する。

**Comment by shutainer** [comment]
宜しくお願い申し上げます。

**Comment by findex-miyakawa** [comment]
gitactionを見る限り、developの最新はビルドを通っています。
fetch、pullをした後にかくにんできますか？

**Comment by findex-miyakawa** [comment]
ちなみにこの依頼は、markdownの記載に関する指摘になります。

**Comment by kis-hirayama** [comment]
ユースケースレベルではMustSupportを付与してよいと全体WGで決まったはずだが。
担当：放射線チーム

**Comment by findex-miyakawa** [comment]
MustSupportを残すのであれば、FSH側にMSを記載をいただくようにお願い致します。
