### ISSUE TITLE
swg2 ImagingStudy-RadiologyのMustSupport定義

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#194]
### 概要
ImagingStudy-RadiologyのMustSupport定義がリソース上はMustSupportがないが、IGの-notesの説明にMustSupportの記述が残っている。

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-imagingstudy-radiology.html

### 修正案
IG側の記述を削除する。

**Comment by kis-hirayama** [comment]
#193 と同様
