### ISSUE TITLE
swg2 Observertion-Commonの説明文書にSnomedを推奨する記述がされている

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#196]
### 概要
Observertion-Commonの説明文書にSnomedを推奨する記述がされている

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-observation-common.html

### 修正しないとどう困るか
Snomedを推奨することにより、これを参照する実装ガイド作成者がライセンス問題に抵触するおそれがある。

### 修正案
Snomedについては、ライセンス問題を解決しない限り使用しない記述もしくは関連する記述をすべて削除する。

**Comment by kis-hirayama** [comment]
担当：石原さん
