### ISSUE TITLE
swg2 ImagingStudy Radiologyのサンプルファイルを作成してほしい

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#200]
### 概要
ImagingStudy Radiologyのサンプルファイルを作成してほしい

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-diagnosticreport-radiology.html

### 要望背景

- リソースおよびサンプル整合性チェック
- 他のプロファイルとの統一性

### 修正案
すでにDiagnosticReportのinlineの定義でimage studyがあるので、これをexample化すればよいのでは？

**Comment by kis-hirayama** [comment]
担当：上中さん
