### ISSUE TITLE
swg4 Allergyintoleranceのサンプルファイルを作成してほしい

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#202]
### 概要
Allergyintoleranceのサンプルファイルを作成してほしい
現在fshファイルがあるが、コメントアウトされた状態

### 依頼先
SWG4

### 該当ページ
なし

### 要望背景
- 全体で統一したい
- 利用しやすくするため

**Comment by ykawazoe** [comment]
現状の最新のプロファイルに準じて作成しました。

**Comment by findex-miyakawa** [comment]
確認しました。
対応ありがとうございました。
