### ISSUE TITLE
swg4 Conditionのexampleに関する指摘

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#203]
### 概要
Conditionのexampleに関する指摘

1. severityにsnomedの項目が入っている。
2. categoryやcodeやbodySite、evidenceのsystemに***と記載されている。

### 依頼先
SWG4

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/Condition-jp-condition-example-1.json.html

### 修正しないとどう困るか
- ライセンス違反に抵触する可能性あり
- ***については利用者側は理解しずらいと感じる可能性あり。

**Comment by ykawazoe** [comment]
SNOMEDを使わないようにして、現状の最新のプロファイルに準じて修正しました。

**Comment by findex-miyakawa** [comment]
確認しました。
対応ありがとうございます。
SWG2では、bodySiteはICD10を利用するという話があったので、どこかの段階で横展開ができればよいと考えています。
