### ISSUE TITLE
swg4 Procedureのサンプルファイルに関する指摘

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#204]
### 概要

1. category.text, code.textが”・・・”となっているが意味のある文章にしたほうがよい
2. category.coding.systemのurlに***の記載がある
3. code.coding.codeはdemo_cataract_surgeryは存在ていますでしょうか？

### 依頼先
SWG4

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/Procedure-jp-procedure-example-1.json.html

**Comment by ykawazoe** [comment]
最新のプロファイルに準じて修正しました。

**Comment by findex-miyakawa** [comment]
対応ありがとうございました。
