### ISSUE TITLE
swg4 JP_ProcedurePerformerRoleCode_CSの名前変更の検討

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#211]
### 概要
JP_ProcedurePerformerRoleCode_CSは、swg3のpractitinerRole.codeも利用する予定。
valueSetはそれぞれのResourceで用意するかもしれないが、
CodeSystemは共通利用できるように名称に変更してほしい。

### 依頼先
SWG4

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/CodeSystem-jp-procedure-performer-role-codes-cs.html

### 要望背景
swg3のpractitinerRole.codeデモ利用できること。

### 修正案
【現状】
JP_ProcedurePerformerRoleCode_CS
【修正案】
JP_PractitionerRoleCode_CS

**Comment by ykawazoe** [comment]
ありがとうございます。対応しました。名称は「JP_PractitionerRoleCodes_CS」とCodesに整えています。
https://github.com/jami-fhir-jp-wg/jp-core-v1x/commit/e85accb83e173d8b579e992620322cdf1eae8652
なお、現状このCSコンテンツは職種ベースの用語ですが、今後は役割ベースの用語に変更予定です（SWG6）

**Comment by findex-miyakawa** [comment]
修正ありがとうございました。確認いたしました。
職種と役割とCodeSystemとしてはわけて、ValueSetとしては束ねるという形ですかね。
修正したら対応したします。
