### ISSUE TITLE
swg2 Observation_LabResultに「ss-mixメモ」、【要検討】のコメントが残っている

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#212]
### 概要
Observation_LabResultにss-mixメモのコメントが残っている

### 依頼先
SWG2

### 該当ページ
JP_Observation_LabResult.fsh

### 修正しないとどう困るか
利用者側に混乱が生じる

### 修正案
前後文脈の正しさを確認後、メモを削除する。

**Comment by kis-hirayama** [comment]
削除します。
担当：検体検査チーム
https://github.com/jami-fhir-jp-wg/jp-core-v1x/blob/develop/input/fsh/profiles/JP_Observation_LabResult

**Comment by findex-miyakawa** [comment]
対応済み
