### ISSUE TITLE
swg2 説明文書の記載の強調文字が残っている

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#218]
### 概要

` `強調文字` ` よる文字装飾が残ってる
以前の話し合いの結果、消していただくことになっていたと思います。

### 依頼先
SWG2

### 該当ページ

-intro.md, -notes.md全般

### 修正しないとどう困るか

他のSWGとの見た目が変わってしまいます。

**Comment by kis-hirayama** [comment]
担当：石原さん
