### ISSUE TITLE
swg2 ImagingStudy RadiologyのlateralityのバインディングがSNOMED CTを指定している

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#264]
### 概要
ImagingStudy Radiologyのlateralityのバインディングの中身がSNOMED CTが指定されている。
コードの種類も少ないので、JP Core側で実装すべきと考える

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-imagingstudy-radiology.html

### 修正しないとどう困るか
- ライセンス違反と取られる可能性がある

**Comment by ishihara-jp** [comment]
@findex-miyakawa 

> ImagingStudyはDICOM画像のメタデータの一部を表現しており、DICOM規格の中でLateralityのコードの既定としてSNOMED-CTの採用が示されている。このため、日本要件のコードを割り当てていない。ただし、この件はSWG6との確認が必要。
>（SWG2 塩川）

だそうです！

**Comment by findex-miyakawa** [comment]
利用者側からすると迷ってしまうのではないかと思いますので、方針提示をしてもらえるとよいと思います。

swg5では、DICOMとは別ですが、下記のコードシステムにて、位置関係を表しているようです。
http://terminology.hl7.org/CodeSystem/v2-0495

**Comment by HERMITRION** [comment]
ishihara-jpさんのコメントに対して補足ですが，DICOM規格の中ではLateralityのコードの規定は独自で作成されており，SNOMED-CTとはマッピングによる対応が行われています．
したがってDICOMが示すLateralityにはR, LもしくはR, L, Bの指定が入りますが，不明な場合は空白を許容しているので実際のデータには何も指定されていないことが多いです．

なお，DICOMが示すLateralityはseries単位のものとimage単位のものがありますが，series単位のものはR, Lしか指定できず，両側を表すBはimage単位のLateralityにしか規定がありません．（理由は不明ですが）
また，series単位での指定はimage単位のものに記載がない場合のconditional requiredにはなっています．

以上のことより割り切って考えると
1.  DICOMのLateralityを参照し，コードが割り当てられていればそれを入れる (R, L が期待される - 厳密にはDICOM規約違反ではあるがBが入ることもありうるか？Bが入る場合はhttp://terminology.hl7.org/CodeSystem/v2-0495との整合性をどうするか決めておく必要がある．）
2. DICOMで空白の場合はクライアントシステム側でR, L, BILを設定することを許容する．（無指定も許容．BかBILかの取り決めは上記と同様に必要）
とするのが良いかと考えますが，SWG2での議論に提案したいと思います．

**Comment by HERMITRION** [comment]
先の放射線部会の議論をもとに、取り急ぎ、JJ1017Pの左右コードへのバインディング(example)に設定し、SNOMED-CTへのバインディング記述をオーバライドしました。
あくまでもデフォルトはDICOMの定義に従いますが、記述がない場合はJJ1017Pの利用を許容するというスタンスです。

**Comment by HERMITRION** [comment]
JJ1017Pをバインディングに定義すると本来DICOMの定義であるものが、JJ1017Pがデフォルトであると誤解される恐れがある。
StructureDefinitionでのJJ1017Pへのbindingは削除する。
本家のDICOM定義へのbindingもwarningを出しているのでこちらは別途解決策を検討する。

**Comment by findex-miyakawa** [comment]
下記の記述がありますが、本カラムはDICOMで利用されるSnomedは契約していない国でも利用可能の中に入りますでしょうか？

https://www.dicomstandard.org/about-home/relations

DICOM and SNOMED have a license agreement that permits the use a subset of SNOMED-CT free for use, both for publication in DICOM as well as by implementers and users of DICOM-compliant products globally, without restriction to SNOMED member countries.

**Comment by HERMITRION** [comment]
はい、その通りSNOMEDと契約していない国での利用でもfreeであることを相互に確認しているという意味になるので、DICOM内で定義されているSNOMED CTのサブセットを使う範囲ではライセンス違反にならないと考えます。

もしこれがライセンス違反になるのであれば放射線機器を導入している国でSNOMEDと契約していない国はすべてライセンス違反をしていることになりますので。

**Comment by findex-miyakawa** [comment]
https://build.fhir.org/imagingstudy-definitions.html
を見ると、series.bodySiteについては、DICOMであることの記述（DICOM Part 16 Annex L ）があるのですが、
series.lateralityについてはDICOMであることを記述を私のほうで見つけることはできませんでした。
DICOMの中で利用されているSNOMED CTであれば、freeと解釈できますが、この対象かどうかはわかりますでしょうか？

**Comment by HERMITRION** [comment]
ImagingStudyそのものがDICOM画像を扱うリソースとして定義されており、mappingでlateralityはDICOM tagの(0020,0060)
が該当すると記述されています。
https://dicom.innolitics.com/ciods/cr-image/general-series/00200060
https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.3.html#table_C.7-5a

**Comment by findex-miyakawa** [comment]
情報ありがとうございます。
私の認識違いで申し訳ありません。
SNOMED CTのライセンスに問題がないで、本Issueは取り下げ致します。
