### ISSUE TITLE
swg2 DiagnosticReport LabResult のサンプルをファイル化してほしい

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#267]
### 概要
DiagnosticReport LabResult のサンプルをファイル化してほしい
現状JLAC10等の指定がないため、サンプルが作れない状況にある。

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-diagnosticreport-labresult.html

### 要望背景

- 全体統一のため、本プロファイル以外はファイル化が行われている。

**Comment by shutainer** [comment]
エラーがでました。
categoryのURLを'http://terminology.hl7.org/CodeSystem/v2-0074'を使え、ということですが、これをAliasesに追加して、aliaseとしてcategoryに指定してもよいのでしょうか？

どのコード体系を利用すべきか、について、全体の議論を把握できていないせいか、よく理解しておりません。

あと、resulutで、ObservationLabResult/jp-observation-labresult-example-1が指定できないようです。

`ERROR: DiagnosticReport/jp-diagnosticreport-labresult-example-1: DiagnosticReport.category[0].coding.system: Value is 'http://terminology.hl7.org/CodeSystem/observation-category' but must be 'http://terminology.hl7.org/CodeSystem/v2-0074'
ERROR: DiagnosticReport/jp-diagnosticreport-labresult-example-1: DiagnosticReport.category[0].coding.code: Value is '検体検査' but must be 'LAB'
ERROR: DiagnosticReport/jp-diagnosticreport-labresult-example-1: DiagnosticReport.category[0].coding[0]: Unknown Code http://terminology.hl7.org/CodeSystem/observation-category#検体検査 in http://terminology.hl7.org/CodeSystem/observation-category for 'http://terminology.hl7.org/CodeSystem/observation-category#検体検査'
ERROR: DiagnosticReport/jp-diagnosticreport-labresult-example-1: DiagnosticReport.result[0]: Unable to resolve resource with reference 'ObservationLabResult/jp-observation-labresult-example-1'`

**Comment by kis-hirayama** [comment]
`JP_DiagnosticReport_LabResult`の`category`については、固定値を使用するよう[StructureDefinition](https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-diagnosticreport-labresult.html#profile)で定義しているので、サンプルもそれに合わせてもらえますでしょうか。

**Comment by findex-miyakawa** [comment]
幾つか修正を行い、整合性とエラーが出ないように変更しました。

**Comment by shutainer** [comment]
修正いたします。

**Comment by findex-miyakawa** [comment]
@shutainer 
先ほどの修正で対応しています。

**Comment by shutainer** [comment]
> 先ほどの修正で対応しています。
ありがとうございます。
ビルドが通っているようでした。
closeいたします。
