### ISSUE TITLE
swg5 medicationに対する薬剤バインディングの付与

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#304]
### 概要
medicationに対する薬剤バインディングがされていない
※CodeSystemはTerminologyServerにあるべきであるが、まずはバインディングだけでも登録してほしい。

### 依頼先
SWG5

### 該当ページ
修正案のページを参照のこと。

### 修正案
下記の内容を参照のこと。

[JP_Medication.fsh](https://github.com/jami-fhir-jp-wg/jp-core-v1x/commit/f668111000b6adab1a039d3f141e8b2ac8f997a8#diff-f0e993f22cdfe135a207a002a9960e67e5ecb4973076a5bfda9547f49f32fcd3)

[JP_MedicationAdministration.fsh](https://github.com/jami-fhir-jp-wg/jp-core-v1x/commit/f668111000b6adab1a039d3f141e8b2ac8f997a8#diff-445870b83f108e3fca812a6a48406e9e4043599b0cada3a0ed9c66a10acb5680)

[JP_MedicationDispenseBase.fsh](https://github.com/jami-fhir-jp-wg/jp-core-v1x/commit/f668111000b6adab1a039d3f141e8b2ac8f997a8#diff-0e722cf3c458662b75050ede042289f8352842e729afa08d6b76afdedf8f487b)

[JP_MedicationRequestBase.fsh](https://github.com/jami-fhir-jp-wg/jp-core-v1x/commit/f668111000b6adab1a039d3f141e8b2ac8f997a8#diff-69fad91a2c2639094bd5658c70eaaaf469de6037bc807aaadc1e91b879e26e9d)

**Comment by skoba** [comment]
薬剤コード指定のためにSlicingが必須となると、影響の範囲が広くなりすぎて大規模な仕様変更となります。ここでは扱っておりませんが、GS1などの規格や、コードシステムにない薬剤の使用も想定されるため、slicingは見送っておりました。
どうしても必要と言うことであれば、次期リリースで検討します。
