### ISSUE TITLE
swg5 MedicationRequestBase.dosageInstruction.doseAndRate.dose[x]のCodeSystemが限定される

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#314]
### 概要
MedicationRequestBase.dosageInstruction.doseAndRate.dose[x]のsystemがSlicingせずにsystemが固定として定義されている。
このため他CodeSystemのurlを許容していないため、CodeSystemを強制している。
ローカルコードも利用できないのはJP Coreとしては不適切だと考える。

### 依頼先
SWG5

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-medicationrequestbase.html

### 修正しないとどう困るか
CodeSystemが限定されてしまう

### 修正案

- 案１）バインディング強度をRequired以外を指定した上で、ValueSetを指定する。
- 案２）Slicingを定義した上で、Fixed Valueを指定する。

上記にてCodeSystemの限定は解かれるが、利用する側からすると案１がわかりやすい

**Comment by skoba** [comment]
現行のVer 1.0.0でFixed valueになっています。JAHIS処方データ交換規約，注射データ交換規約では空欄を認めているので，preferredに変更します。
