### ISSUE TITLE
swg5 subsutitution.allowed[x]のバインディング

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#317]
### 概要
subsutitution.allowed[x]の後発品変更可不可についてCodeになっているため、CodingSystemを作成し、割り当ててほしい

### 依頼先
SWG5

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-medicationrequestbase.html

**Comment by tmskmr** [comment]
処方情報HL7FHIR記述仕様の後発品変更不可コード(urn:oid:1.2.392.100495.20.2.41)を使用すべき
1：後発品変更不可、2：剤形変更不可、3：含量規格変更不可
