### ISSUE TITLE
swg5 MeditaionDispenseBase.Quantity.Codeの単位マスタとのバインディング

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#319]
### 概要
MeditaionDispenseBase.Quantity.Codeに単位のコードシステムに対してバインディングすべきでは

### 依頼先
SWG5

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-medicationdispensebase.html

**Comment by tmskmr** [comment]
内服・外用処方と注射で使い方が異なるので、JP_MedicationDispense, JP_MedicationDispense_Injectionでそれぞれバインディングした方がよいと思います。
