### ISSUE TITLE
swg5 MedicationDispnseBase.performer.functionのバインディングを割り当ててほしい 

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#320]
### 概要
MedicationDispnseBase.performer.functionに日本のバインディングを割り当てるべきでは

[JP_PractitionerRoleCodes_CS](https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/CodeSystem-jp-practitioner-role-codes-cs.html)
を割り当てるのがよいと思われる。

### 依頼先
SWG5

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-medicationdispense.html

**Comment by tmskmr** [comment]
このperformerは調剤時の役割に限定されているので、オリジナルのバインディングで問題ないと思います。

**Comment by findex-miyakawa** [comment]
御指摘の通りです。取り下げます。
