### ISSUE TITLE
swg5 MedicationAdministratonBase.performer.functionのバインディングを割り当ててほしい

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#321]
### 概要
MedicationAdministratonBase.performer.functionに日本のバインディングを割り当てるべきでは

[JP_PractitionerRoleCodes_CS](https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/CodeSystem-jp-practitioner-role-codes-cs.html)
を割り当てるのがよいと思われる。

### 依頼先
SWG5

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-medicationadministration.html

**Comment by tmskmr** [comment]
このperformerは投薬実施時の役割に限定されているので、オリジナルのバインディングのままでよいと思います。

**Comment by findex-miyakawa** [comment]
おっしゃる通りですね。取り下げます。
