### ISSUE TITLE
swg5 サンプルにある静脈注射の表記が間違っている

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#328]
### 概要
サンプルにある静脈注射のコードが

urn:oid:1.2.392.200250.2.2.20.40#30 "静脈注射"
→
urn:oid:1.2.392.200250.2.2.20.40#30 "注射"
に変更

### 依頼先
SWG5

### 備考
IG Publisherにて警告になっていたため。

**Comment by skoba** [comment]
コードは合っているように思うんですけども。Terminologyチェックでエラーが出ているんでしょうか。

**Comment by skoba** [comment]
CodeSetを修正
