### ISSUE TITLE
swg2 Observation_LabResultの説明にSnomedコードを検索の記述がある

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#349]
### 概要
Observation_LabResultの説明にSnomedコードを検索の記述がある
SearchParameterの部分の説明

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-observation-labresult.html#%E6%93%8D%E4%BD%9C%E8%A9%B3%E7%B4%B0

### 修正しないとどう困るか

 - ライセンス違反に抵触する恐れあり

**Comment by shutainer** [comment]
snomedの記載箇所を削除。
だが、valueCoadableConceptにsnomedct以外のコード体系を当て嵌めなければならないかもしれないかどうか,
は不明。
