### ISSUE TITLE
swg4 全般shortの記載がない項目が見受けられる

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#357]
### 概要
defineやcommentに日本語の説明があるが、shortに記載ものがある。

特にJP Coreで定義変更した項目については少なくともshortにも説明を加えてもらえるとわかりやすいと思います。

### 依頼先
SWG4

### 該当ページ
fshファイル全般

**Comment by ykawazoe** [comment]
全般的にshortを追記しました。

**Comment by findex-miyakawa** [comment]
対応ありがとうございました。
