### ISSUE TITLE
swg4 AllergyIntoleranceの注意事項の詳細化

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#358]
### 概要
AllergyIntoleranceの注意事項が英語＋リンク（内容も英語）になっている。
どのような内容なのかを日本語で説明してもらえるとわかりやすと思います。

### 依頼先
SWG4

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-allergyintolerance.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A0%85

**Comment by ykawazoe** [comment]
注意書きへのご意見募集中です。

==
* アレルギーの否定表現についての注意事項
- 本プロファイルが継承するプロファイル（AllergyIntolerance v4.0.1）においては、既知のアレルギーがないことを表現するために「SNOMED CT: 716186003 |No known allergy (situation)|)」を用いることが例示されている。一方で、本プロファイル JP_AllergyIntolerance.codeのValue Setとして例示する「JP Core AllergyIntolerance ValueSet」には「No known allergy」等に相当する表現がない。そのため、本プロファイルを継承するプロファイルが、「JP Core AllergyIntolerance ValueSet」を利用する場合には、否定されたアレルギーを表現するために、アレルギーの有無を区別する要素を追加するなどの措置を取ることを想定している。なお、本プロファイルは「JP Core AllergyIntolerance ValueSet」の利用を要求・推奨するものではないため、他のValue Setを使う選択肢もある。
参考：Negated Allergies and Intolerances. [https://hl7.org/fhir/R4/allergyintolerance.html#9.1.3.3](https://hl7.org/fhir/R4/allergyintolerance.html#9.1.3.3)

**Comment by findex-miyakawa** [comment]
対応ありがとうございました。
