### ISSUE TITLE
swg4 condition.codeの説明

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#359]
### 概要
condition.codeについてv1.1での用語の完成は難しいと聞いていますが、予定や対応方針について何かしら記述することができますか？
日本国内での標準について検討いる旨だけでも記載があるとよいと考えます。

### 依頼先
SWG4

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-condition.html

**Comment by ykawazoe** [comment]
下記のような補足を追記しようと思います。あくまで補足のためどこに入れようかと迷いますが、notes.mdの##注意事項のところでよろしいでしょうかね？他に適当なところがありますでしょうか。

==
Condition.codeについて、本プロファイルを継承するプロファイルが想定する用途に応じて、ICD-11などをCode SystemとするValueSetを独自に設定することを想定している。
==

**Comment by findex-miyakawa** [comment]
現在作成中である旨と上記の記載があれば、よいと思います。
LocalCodeやテキスト記載にて回避できる件は、ガイダンスとして全体のところで記載するようにします。

注意事項の場所でよいと思います。

**Comment by ykawazoe** [comment]
ありがとうございます。注意事項に補足を記載しました。
==
Condition.codeについての補足。現時点では、患者の状態を包括的に含む適当な日本語用語集がないと考え、基底のValue Setを継承するにとどめている。そのため、本プロファイルを継承するプロファイルがその用途に応じて、MEDIS標準病名マスタやICD-11などをCode SystemとするValue Setを独自に設定することを想定している。
