### ISSUE TITLE
swg4 procedureの未完成の用語について

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#360]
### 概要
procedureの未完成の用語の扱いについて
別途Slack等にて調整をさせてください。

### 依頼先
SWG4

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-procedure.html

https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/ValueSet-jp-procedure-codes-ichi-vs.html
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/ValueSet-jp-procedure-condition-vs.html
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/ValueSet-jp-procedure-reason-vs.html
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/ValueSet-jp-procedure-device-action-vs.html
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/ValueSet-jp-procedure-devicekind-vs.html

**Comment by ykawazoe** [comment]
ご指摘の５個に加えて、JP_ProcedureFollowUp_CSを修正しました。aliases-jpcore.fshのURLを変更しています。

Alias: $JP_ProcedureCodesICHI_CS = http://jpfhir.jp/fhir/Common/CodeSystem/JP_Undefined_CS
Alias: $JP_ProcedureCondition_CS = http://jpfhir.jp/fhir/Common/CodeSystem/JP_Undefined_CS
Alias: $JP_ProcedureReason_CS = http://jpfhir.jp/fhir/Common/CodeSystem/JP_Undefined_CS
Alias: $JP_ProcedureDeviceAction_CS = http://jpfhir.jp/fhir/Common/CodeSystem/JP_Undefined_CS
Alias: $JP_ProcedureDeviceKind_CS = http://jpfhir.jp/fhir/Common/CodeSystem/JP_Undefined_CS
Alias: $JP_ProcedureFollowUp_CS = http://jpfhir.jp/fhir/Common/CodeSystem/JP_Undefined_CS
