### ISSUE TITLE
swg2 ImagingStudyのProcedureCodeの要求レベル

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#361]
### 概要

http://playbook.radlex.org/playbook/SearchRadlexAction から取得されるべき(SHALL)である。

バインドの指定: extensible(適用可能なものがあれば使わなければならない）
日本語の説明：推奨（~すべき）
要求レベル：必須(SHALL)

となっており、どのレベルで要求されているのか分かりにくい。

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-imagingstudy-radiology.html#profile

### 修正案
本来の定義のように、extensibleの説明を記載すればよいのでは？

**Comment by HERMITRION** [comment]
すみません。これは本家の記載がそうなっていたので、そのまま訳してしましました。
ご指摘の通りですね。
修正します。
