### ISSUE TITLE
swg2 DiagnosticReport_Radiology.codeの指定

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#369]
### 概要
codeをloinc#18748-4のみに固定していますが、もう少し緩やかにするのはどうでしょうか？
放射線レポートの中で、CRやMR、CTなどのレポートについて区別をしたいという要望があるように思います。

例えば、[Radiology studies (set) 18748-4](https://loinc.org/26443-2/)配下のコードをvalueSetとして作成し、
バインディング強度をPrefferedで作成すれば、code.codingの中にローカルコードも入れることができ、
柔軟性があがるように思います。

是非検討のほどお願いします。

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-diagnosticreport-radiology.html#profile

**Comment by HERMITRION** [comment]
本コードについてはSWGで議論していますが、本家でLOINC指定(preferedですが)されています。バインディング強度はpreferedで構わないと思っています。

DiagnosticReport_Radiology.codeはcardinalityが1..1で複数のコードを許容していないと思われることが一つと、LOINCでお示しいただいているRadiology-setは本邦での検査の範囲として必ずしも粒度が一致しません。
（記載されているもの以外に複数の範囲の組み合わせが存在するため、LOINCの様なコード体系では表現が難しい --> この点においてはJJ1017が適切であるがが、一方でJJ1017では一つのコードでその検査を包括的に表現できない場合がある。典型的にはMRI + MRAの検査。頭部の検査では一般的であるが、これをJJ1017で表現するには少なくとも二つのコードが必要。）

そこで、少なくとも放射線検査に関するレポートであることをここでは示しておいて、DiagnosticReport.categoryでCTやMRI等のコードを付与することによりレポートの区別をすることを意図しています。ここでは複数のコードを許容しますので、対応が容易です。

一方でDiagnosticReport.categoryは最低限「RAD]が入ることを意図して作業を進めておりましたが、ご指摘の様に固定値となっている点は問題がありますので、#368のissueにはご提案いただいた形で対応することが妥当かと思います。それを解決すれば、ローカルコードの設定は自由なので、ご懸念の用途には対応できると思われます。

**Comment by findex-miyakawa** [comment]
IGPublisherのビルド結果を見ると、(exactly)を指定しなくても
Fixed Value: 18748-4
となってしまいます。
valueSetとしてはprefferedになっていますが、CodeとしてはfixedValueの値のみしか利用できなくなっています。

Preferredにするために、技術的に回避する方法としては、
１件のみのValueSetを作成し、これを指定する方法ぐらいでしょうか。

preferredにて１件のみというのは違和感があったので、上記のSetを提案させていただきました。

**Comment by HERMITRION** [comment]
なるほど。fixedValueになってしまうのはIGの仕様なのですね。

スタンスとしてはpreferredなのですが、基本的にここに他のコードを入れられても困ってしまうのでfixedValueのままで良いかもしれません。（上に書いたようにcategoryの方で複数のコード指定ができるので。）
valueSetの方を変更してfixedValueにしてしまうのはどうでしょうか。

一応ここをpreferredにして残している理由は、本家のcodeに関する説明で「すべての用語の使用がこの一般的なパターンに適合するわけではない。 場合によっては、モデルにcodeableConceptを使用せず、コーディングを直接使用して、テキスト、コーディング、翻訳、および要素間の関係と事前調整および事後調整を管理するための独自の構造を提供する必要がある。」というような記載があり、codeableConcept以外で指定することもありうるのだと判断したからです。ただ、非常に紛らわしいのと、ここは放射線レポートに特化していますので、fixedValueの決め打ちで良いと思います。

**Comment by findex-miyakawa** [comment]
fixedValueだとあまり融通が利きません。
試しにExampleにて、Codeを利用せずに、テキストのみを記載すると、

「he element text is present in the instance but not allowed in the applicable fixed value specified in profile」のエラーが出力されます。

```
// * code = http://loinc.org#18748-4 "Diagnostic imaging study"
* code.text = "核医学レポート"
```

試しに提案したValueSetを検討のために作成するようにします。

**Comment by HERMITRION** [comment]
了解しました。
今週末にSWG2の会合があるはずなので、そこでも議論してみます。

**Comment by findex-miyakawa** [comment]
1件のみのValueSetを作成しました。
これだとfixedValueにならないので、他のコードやテキストのみという運用も可能になります。

[プロファイル](https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/feature/swg2-DiagnosticReportRadiologyCode%E3%81%AE%E6%8C%87%E5%AE%9A/StructureDefinition-jp-diagnosticreport-radiology.html#profile)

[コード指定しないケース](https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/feature/swg2-DiagnosticReportRadiologyCode%E3%81%AE%E6%8C%87%E5%AE%9A/DiagnosticReport-jp-diagnosticreport-radiology-example-2.json.html)

**Comment by HERMITRION** [comment]
#395 で解決
