### ISSUE TITLE
swg2 diagnosticreport-radiologyの説明文書が横スクロールが大きく発生する。

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#371]
### 概要
textの説明のコード部分が１行に大量に記載されているために、横スクロールが発生している。

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-diagnosticreport-radiology.html#text

### 原因
textの説明部分にて、text.divが１行に大量に記載されているため。

### 修正案
- 案1) divの部分の途中に改行をいれ、見やすくする。
- 案2) swg5でやったようにクリックしたら表示するように仕組みを入れる。

**Comment by HERMITRION** [comment]
海外で実際に提供されている例でもこの部分はxhtmlの表記で、このように一連のデータとして表現されています。実際のexampleのイメージをつかんでいただくためにはあえてここを成型する必要が無い（成形することで逆に文書への整形を必要とすると誤解される恐れもある）と考えています。
案２については具体的にどのようにされているのか認識できておりませんので、詳しくお教えいただければ幸いです。

**Comment by findex-miyakawa** [comment]
案２については下記を考えていましたが、xhmlタグを含む文章だと利用できないのを確認しました。
https://github.com/jami-fhir-jp-wg/jp-core-v1x/issues/131

そもそもはIG側の問題ですので、CSSで対応できないかを試してみます。

**Comment by findex-miyakawa** [comment]
JPCore.cssに下記を加えることで、コードの横幅最大値を指定しました。

pre[class*="language-"] {
    max-width: 1000px;
}
