### ISSUE TITLE
swg2 DiagnosticReport Radiologyの関連するプロファイルの参照・被参照の文言を消去してほしい

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#373]
### 概要
DiagnosticReport Radiologyの関連するプロファイルの参照・被参照の文言を消去してほしい
参照：Text Summaryのタグで自動的に記載される。

手動記載と自動記載の不整合を発生させないためにも、手動側を消すことで全体会議にて合意があったため。
被参照は自動記載されないが、重要項目ではないことと相手側のプロファイルに記載されていることはわかるため、あえて記載しないこととなった。

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-diagnosticreport-radiology.html#%E9%96%A2%E9%80%A3%E3%81%99%E3%82%8B%E3%83%97%E3%83%AD%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB

### 修正しないとどう困るか

- 統一性が失われます。

### 原因
sushi & IG Publisher移行により自動的に参照関係を出力されるようになったため。

**Comment by HERMITRION** [comment]
参照・被参照部分のみの削除で良いでしょうか。

関連するプロファイル（リソース）については放射線レポートを作成するにあたり意識すべきリソースであり、bundle documentとなる場合に重要なリソースになります。ユースケースベースで作成しており、自動的に参照関係を表現できない部分になりますので、こちらは残したいと思っています。

上記につきご確認いただいた後に、作業したいと思います。

**Comment by findex-miyakawa** [comment]
「参照・被参照部分のみの削除で良いでしょうか。」
はい。この部分だけの削除で問題ございません。

その他の記載については、自動記載ではない情報が記載されておりましたので、残していただくので問題ございません。
