### ISSUE TITLE
swg2 ImageStudy_ExampleのBodySiteのCodeSystemがDicomになっていない

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#374]
### 概要
ImageStudy_ExampleのBodySiteのCodeSystemがDicomになっていない。
http://jpfhir.jp/Common/CodeSystem/JP_ImagingStudy_BodySite_CSが見つからないというエラーがでている。

### 依頼先
SWG2

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/ImagingStudy-jp-imagingstudy-radiology-example-1.json.html

**Comment by HERMITRION** [comment]
JP_ImagingStudy_BodySite_CS については宮川さんに修正いただいたexampleになるかと思いますが、本家のCodeSystemでのDICOM定義URLでも警告が発生している部分になります。JP Coreの中で、CodeSystemを再定義した方が良いでしょうか？

DICOMのページ https://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_29.html にFHIR JSONへのリンクはあるのですが、コンテンツが整備されていない様に見えます。

**Comment by findex-miyakawa** [comment]
本件私のほうで修正します。
FSH上はFHIR BASEになっているため、JP CoreのBODY SITEではなく、CodeSystemとしてSnomedを指定する予定です。

DICOMのhtmlを指定しているためにエラーになっている件については、FHIR BASE側の問題だと認識しましたので、警告が発生しないように、
[ignoreWarnings.txt](https://github.com/jami-fhir-jp-wg/jp-core-v1x/blob/develop/input/ignoreWarnings.txt)
に追記して発生しないように対処しました。

**Comment by HERMITRION** [comment]
ありがとうございます。

一点だけ確認です。

SNOMEDを指定する際にDICOM側でmappingされているSNOMEDの範囲を超えると、先日議論したライセンスの問題が発生しうるとは思います。
IG上で直接SNOMEDを指定しておいても大丈夫でしょうか？

**Comment by findex-miyakawa** [comment]
exampleとしてはBodyPartExamineの範囲のCHESTを指定しようと考えています。

https://dicom.nema.org/medical/Dicom/2015c/output/chtml/part16/chapter_L.html

* series.bodySite = http://snomed.info/sct#T-D3000 "Chest"

**Comment by HERMITRION** [comment]
了解しました。exampleのみの変更ですね。

**Comment by findex-miyakawa** [comment]
先ほどはリタイアしたコードで、正しくは下記のコード表のようです。
https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_l.html

* series.bodySite = http://snomed.info/sct#43799004 "Thoracic cavity"

となるようです。

**Comment by findex-miyakawa** [comment]
Pull Requestを発行しました。
https://github.com/jami-fhir-jp-wg/jp-core-v1x/pull/391

**Comment by HERMITRION** [comment]
変更を確認しました。
エレメント内の要素を指定しなくても一行で書けるのですね。

さて、"Thoracic cavity"の表記ですが、SCTではそちらですが、DICOMのBody Part Examined (0018,0015)では"CHEST"の表記になっています。
Table L-1. に従うと"CHEST"の方がよさそうにも思います。
bodySite.display = "CHEST"とはしない方が良いのでしょうか？

もう一つ、私にはmergeの権限が無いので、最終的にはKIS平山さんにリクエストしていただければ幸いです。

**Comment by findex-miyakawa** [comment]
Display Textなのですが、Snomedのほうに登録がないとエラーとなり、試しに"Chest"を設定したのですがダメでした。
裏でMapping情報とうがあるのかもしれませんが、現状以下の４つから選択しないと行けないようです。
- Thoracic cavity structure (body structure)
- Thoracic cavity structure
- Pectoral cavity
- Thoracic cavity

DICOM内でのSNOMEDの利用については、Markdownのなかで触れていただけるとわかりやすいと思います。

**Comment by HERMITRION** [comment]
情報をありがとうございます。

コードシステムをSNOMEDにするとdisplayもSNOMEDの表記をする。
コードシステムにDICOMを定義する場合は”CHEST”などのBody Part Examinedに定義される値を使う。

という理解で良いでしょうか。

**Comment by findex-miyakawa** [comment]
NEMAがDICOM用に用語セットを作ってもらえば、Body Part Examinedベースの形になるので、前述の理解で正しいと思います。
