### ISSUE TITLE
swg3 Patient Identifierに関するSearch Parameterの例は施設OIDが適切

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#381]
### 概要
Patient Identifierに関するSearch Parameterの例は施設OIDが適切に思える。
Identifierの説明にてOIDを推奨しているが検索例では施設のCannnocal URLを指定している。

### 依頼先
SWG3

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-patient.html#search-parameter%E4%B8%80%E8%A6%A7

**Comment by kaminaka-salesforce** [comment]
StructureDefinition-jp-patient-notes.md
該当箇所を以下の内容で修正
| SHALL            | identifier    | token  | GET [base]/Patient?identifier=urn:oid:1.2.392.100495.20.3.51.11312345670\|123456 |

**Comment by Shunsuke-Doi** [comment]
SWG3上中さんが対応しました。
