### ISSUE TITLE
swg3 Coverage.subcriberに公費受給者番号を設定するにはどうすればよいか

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#384]
### 概要
Coverage.subcriberに公費受給者番号を設定するにはどうすればよいか
指定されている型は、PatientおよびRelatedPersonになっており、説明にある公費受給者番号を入れることはできないと思われる。

### 依頼先
SWG3

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-coverage-definitions.html#Coverage.subscriber

**Comment by Shunsuke-Doi** [comment]
subscriberの「公費受給者番号」記述はsubscriberidの方が正しいので、削除する形で対応しました。
