### ISSUE TITLE
swg3 Coverage.Indetifierの検索の要求レベルをShallにしてほしい

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#385]
### 概要
Coverage.Indetifierの検索の要求レベルをShallにしてほしい
他のリソースに合わせてレベルをshould→shallにしてほしい。
合わせてIndentifierに関する利用に関する説明を追記をお願いします。

### 依頼先
SWG3

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-coverage.html

**Comment by Shunsuke-Doi** [comment]
対応しました。
