### ISSUE TITLE
swg3 Location.IdentifierのSearchParameterをSHALLにしてほしい

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#390]
### 概要
Location.IdentifierのSearchParameterをSHALLにしてほしい
他プロファイル統一のため

### 依頼先
SWG3

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-location.html#search-parameter%E4%B8%80%E8%A6%A7

**Comment by Shunsuke-Doi** [comment]
SWG3 檀原さんが対応しました。
