### ISSUE TITLE
swg2 Diagnosticreport-Radiologyの検索パラメータの要求レベル（コンフォーマンス）を記載してほしい

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#393]
### 概要
Diagnosticreport-Radiologyの検索パラメータの要求レベル（コンフォーマンス）を記載してほしい
現在記載だとすべてのパラメータは必須となっているように見える。

用途によっては全てを実装することは難しいため、

identifier　=> SHALL
それ以外  => SHOULD or MAY
に割り当ててほしい。
テーブルについても他のリソース同様に列を追加した上で記載をお願いしたい。

変更後、SWG1にてCapabiltiyStatementへの反映も必要になる。

### 依頼先
SWG2, SWG1

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-diagnosticreport-radiology.html#%E5%BF%85%E9%A0%88%E6%A4%9C%E7%B4%A2%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF

**Comment by HERMITRION** [comment]
検索パラメータの記載について確認です。まず、必須の記載は齟齬があるので修正します。

本家のDiagnosticReportのパラメータをそのまま記載してるのですが、これはcommonに移した方がよさそうにも思います。LabResultにも同様に影響するところなので、SWG2で議論したいと思いますが、もし、Radiologyのみの修正の方が良ければお教えください。

なお、LabResultでもIdentifierはSHALLである方がよさそうであるなど、他のリソースと比べた時の温度差がこの検索パラメータの説明部分には感じられます。（特に検索パラメータの組み合わせの定義を盛り込んでいるところが厄介です。単なる一覧と検索パラメータの組み合わせおよびコンフォーマンスは分離して表記する方が誤解が無いようにも感じています。）

多彩な検索の組み合わせが考えられることと、statusの状態によって存在しない(null)となるエレメントもありうるため、特に複合検索においてはコンフォーマンスを単純に決められません。
おそらくこれまでの議論ではbundle documentなどとしてリソース内容が確定したものに対しての検索ということで書かれているところが多いと思われますので、この点についてどのような見解であるかをお教えいただければ幸いです。

**Comment by findex-miyakawa** [comment]
LabResultと共通化できるようであればCommonに移していただくのがよいと思います。
実際のCapabilityStatementでは、FHIIR Baseのリソースに対して、どの検索パラメータを利用するかを定義した上でSupported Resouceとして派生先のプロファイルを指定しています。
返却のBundleに関してはJP Coreというよりも派生先での要件になってくるので、JP Coreとしてはまずはリソース単体での検索を考えていただくのよいと考えています。

**Comment by HERMITRION** [comment]
了解しました。
まずはSWG2で議論に付します。

その後、commonも含め記載を調整しますので、しばらくお時間をください。
