### ISSUE TITLE
swg3 PractitionerRole.Identifierに関する検索パラメータに対応してほしい

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#394]
### 概要
PractitionerRole.Identifierに関する検索パラメータに対応してほしい

### 依頼先
SWG3

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-practitionerrole.html#search-parameter%E4%B8%80%E8%A6%A7

### 修正しないとどう困るか

- 全体統一のため。

### 修正案

- SHALLにて Identifierの検索を追加
- その他の検索パラメータをSHOULD,MAYに変更

**Comment by Shunsuke-Doi** [comment]
SWG3 檀原さんが対応しました。
