### ISSUE TITLE
表内に記載されたaliasが正しくリンクされない

### ISSUE THREAD

**Issue by HERMITRION** [jami-fhir-jp-wg/jp-core-v1x#422]
### 概要
markdownの"|"で区切られた表内に[JP_Patient]等のalias表記を入れると正しくリンクが作成されない

### 依頼先
SWG名称 or 不明 or 個人
宮川さん、ご確認をいただければ幸いです。

### 該当ページ
DiagnosticReport_common

### 修正しないとどう困るか
適切なリソースへの参照ができない

**Comment by findex-miyakawa** [comment]
{% include markdown-link-references.md %}
分割に上記の一文を追加しました。

これでリンク情報が利用できるようになると思います。

**Comment by HERMITRION** [comment]
ありがとうございます。
確認しました。
