### ISSUE TITLE
swg5 RP内薬剤番号の拡張定義位置の配置先について

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#425]
### 概要
medication RP番号の拡張定義位置不要では。
本来は利用する側での定義になると思うがどうか。

### 依頼先
SWG5

### 該当ページ
medication関連

**Comment by tmskmr** [comment]
オーダー内のRPの順序やRP内の薬剤の順序は依頼医の意図を伝える重要な情報だそうなので、出力側で持っている情報を正確に受信側に伝えるために定義しています。そのまま受信側でも使えとまではいうつもりはなく、どう利用するかは受信側の裁量に任せてよいと思います。

**Comment by findex-miyakawa** [comment]
MedicationRequest_Injectionのほうにあるべきものだと思っていました。

理由としては、MedicationRequest_injiction.medicationCodeableConceptを許容されており、それを利用した際に順序を記載するにはRequest側に定義をしないと行けず、また処方リソースとの統一性から考えていました。

ちなみに定義を見直しましたが、記述上の誤りがあるようです。
【現状】
FSH上定義
RP番号：MedicationRequest_Injection
RP番号順序：Medication

Markdown上
RP番号：定義なし
RP番号順序：MedicationRequest_Injection、Medicationの両方定義

**Comment by tmskmr** [comment]
> MedicationRequest_injiction.medicationCodeableConceptを許容されており
これはFSHの間違いですね。

> 【現状】
> FSH上定義
> RP番号：MedicationRequest_Injection
> RP番号順序：Medication
これは正しいです。

> Markdown上
> RP番号：定義なし
> RP番号順序：MedicationRequest_Injection、Medicationの両方定義
これは間違いです。

ということで、以下の修正を行います。
・FSHファイルで、medicationCodeableConceptは使用できないようにする
・Markdownで、RP内薬剤番号はMedicaitonのみで使用するようにする

**Comment by findex-miyakawa** [comment]
DispenseやAdministrationも、表記・定義ともに揺れがあります。

RP番号がない（fsh, 記述上）
RP内順序のMarkdown上に記述あり

**Comment by tmskmr** [comment]
まとめて修正します。

**Comment by findex-miyakawa** [comment]
FSHについてはリファクタリングの際に対応しました。

@tmskmr 
Markdownの記載をよろしくお願いいたします。

**Comment by findex-miyakawa** [comment]
Markdownの記述も直しました。
