### ISSUE TITLE
fshのcardinality設定が反映されない

### ISSUE THREAD

**Issue by HERMITRION** [jami-fhir-jp-wg/jp-core-v1x#427]
### 概要
1..に変更されていたfshの内容を0..に戻したが反映されない

### 依頼先
SWG名称 or 不明 or 個人
findex-miyakawa

### 該当ページ
diagnosticReport_radiology.fsh

### 修正しないとどう困るか
定義の修正ができず、内容に齟齬が生じる
commonでは問題ないが、派生であるradiologyで修正（v1と同様に戻す）ことができていない。

**Comment by findex-miyakawa** [comment]
対象はどの項目でしょうか？

**Comment by HERMITRION** [comment]
categoryとeffective[x]です。
ご確認のほど、よろしくお願いいたします。

**Comment by HERMITRION** [comment]
追記です。diagnosticReport_radiologyになります。

**Comment by findex-miyakawa** [comment]
1) effective[x]について
* effective[x] 1..
の一文を削除することによって0..1にすることができると思います。

2)categoryのcardinality
RADを必ず１つをいれるようにSlicingを定義しているため、categoryを1以上になっています。

※もともとSlicingせずに、filxedValueは実質1..1になっていました。
より弱めることもできますが、Radiologyを他のDiagnositicReportと区別するために必ず１個入れるというのは問題ないように思います。
少し違いますが、US CoreのObservation_LabResultでは同様の対応を行っています。
https://hl7.org/fhir/us/core/StructureDefinition-us-core-observation-lab.html

**Comment by HERMITRION** [comment]
ありがとうございました。確認しました。
明示的に

- effective[x] 0..1としていたのを削除したら反映されました。

2) ご指摘の通りですね。
他のプロファイルで内部に1..1の要素を持つエレメントが0..1となっているものがあったので、0..1の方が良いかと思っていましたが、ここは1..*で問題ないように思いました。
明示的な
- category 1..
の記述を削除しましたが、IGは1..*となっていますので、そのような仕様であると理解しました。
