### ISSUE TITLE
swg6 PractitionerRoleマスタの更新

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#432]
### 概要
PractitionerRoleマスタの更新
電子カルテベースの職制に変更予定

### 依頼先
SWG6

### 該当ページ
JP_PractitionerRole_CS.fsh

**Comment by takeshi-imai-jp** [comment]
更新致しましたのでcloseにして頂いて結構です。

**Comment by findex-miyakawa** [comment]
対応ありがとうございました。
