### ISSUE TITLE
swg2 DiagnosticReportRagiologyのMustSupport記述

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#447]
### 概要
DiagnosticReportRagiologyのMustSupport記述

- FSHへ対するMSの付与と記述があっていない
  - basedOn : MS属性なし
  - category : 必須要素では？
  - effective[x] : MS属性なし 
  - performer : MS属性なし
  - resultInterpreter :  MS属性なし

最終的なFSHと記述を合わせるようにお願いします。

### 依頼先
SWGS

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-diagnosticreport-radiology.html

**Comment by kis-hirayama** [comment]
@HERMITRION 
田中先生
ご対応ありがとうございます。
確認したところ、リソース構造ではcategoryが必須となっておりますが、文章の必須要素の章ではcategoryの記載がありませんので、お手数ですがご確認の程よろしくお願い致します。

**Comment by HERMITRION** [comment]
理解しました。RADをデフォルトとしたために必須になっていたことを失念していました。

修正しました。
