### ISSUE TITLE
swg5 examples.fshとmarkdownでサンプルインスタンス記述内容に差異が無いようにする

### ISSUE THREAD

**Issue by yoshinori-kodama** [jami-fhir-jp-wg/jp-core-v1x#461]
### 概要
- Medication
  - n/a
- MedicationRequest
  - [ ] identifier.system に差異がある
    - fsh: `http://jpfhir.jp/fhir/Common/IdSystem/resourceInstance-identifier`
    - md: `urn:oid:1.2.392.100495.20.3.11.1.11311234567`
  - [x] 「クリックで展開」の中に記述されているサンプルの不適合
    - identifier.system: `http://www.sample.com/fhir/medication-request` になっている
    - Extension `JP_MedicationDosage_UsageDuration` が、rootに定義されている（正しくは dosageInstruction）
    - dosageInstruction.route.coding.system に差異がある
      - fsh: `http://jpfhir.jp/fhir/Common/CodeSystem/route-codes`
      - md: `urn:oid:2.16.840.1.113883.3.1937.777.10.5.162`
- MedicationDispense
  - [x] fsh側に daysSupply 要素が記述されていない
- MedicationAdministration
  - n/a
- MedicationRequest_Injection
  - [x] 投与速度の記述内容に差異がある
    - fsh: denominator が 1日 になっている → 誤りのため、mdに揃える
    - md: denominator が 1時間 になっている
  - [x] 力価区分の記述内容に差異がある
    - fsh: doseAndRate.type に記述している → 誤りのため、mdに揃える
    - md: Medicationリソースのstrengthに拡張を追加している
  - [x] 指示ラインの canonical url に差異がある
    - fsh: `http://jpfhir.jp/fhir/Examples/CodeSystem/JP_MedicationRequestDosageInstructionLine_CS`
    - md: `http://sample.com/CodeSystem/MedicationRequest-line` → fshに揃える
  - [x] 投与装置の canonical url に差異がある
    - fsh: `http://abc-hospital.local/fhir/devide/local-device-type` → mdに揃える
    - md: `http://terminology.hl7.org/CodeSystem/v2-0164`
- MedicationDispense_Injection
  - [x] 投与装置の canonical url に差異がある
    - fsh: `http://abc-hospital.local/fhir/devide/local-device-type` → mdに揃える
    - md: `http://terminology.hl7.org/CodeSystem/v2-0164`
  - [x] 力価区分の拡張に対する canonical url に差異がある
    - fsh: `http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Medication_IngredientStrength_StrengthType`
    - md: `http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Medication_Strength_StrengthType` → fshに揃える
- MedicationAdministration_Injection
  - [x] 実施投与ラインの記述内容に差異がある
- Immunization
  - n/a
 
### 依頼先
SWG名称 or 不明 or 個人

**Comment by findex-miyakawa** [comment]
マージしていることを確認しました。
