### ISSUE TITLE
ValueSet: JP Core Medication JAMI Additional Usage ValueSetのdisplayにおける数字ズレ

### ISSUE THREAD

**Issue by tmitanitky** [jami-fhir-jp-wg/jp-core-v1x#498]
### 概要
不均等処方の「○回目」の数字がすべて1になっているようです。

V21NNNNN	urn:oid:1.2.392.200250.2.2.20.22	不均等・１回目・１単位量
は「不均等・2回目・１単位量」と思います。

これ部分はどのファイルから生成されていますか。

### 依頼先
SWG5

### 該当ページ
不明

### 修正しないとどう困るか
一部システムにおいて表記が変わってしまうかもしれない。

**Comment by tmskmr** [comment]
仕組みは分かりませんが、ターミノロジーサーバーhttps://tx.jpfhir.jp/のデータをインサートしているようです。
従って、ターミノロジーサーバーのデータを修正する必要がありそうです。

**Comment by findex-miyakawa** [comment]
@skoba @tmskmr 
本件、確認いただけないでしょうか？

**Comment by skoba** [comment]
これ、どうやったら再現するんでしょう？

**Comment by tmitanitky** [comment]
https://jpfhir.jp/fhir/core/1.1.1/ValueSet-jp-medication-usage-jami-additional-vs.html
こちらのページです。

**Comment by tmitanitky** [comment]
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/ValueSet-jp-medication-usage-jami-additional-vs.html
最新版でも同じ表示でした。。
