### ISSUE TITLE
imagingstudyの区別方法

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#518]
### 概要
imagesturyの放射線と内視鏡を区別する方法がない

### 依頼先
SWG2

### 修正しないとどう困るか
検索等を行った際に、両方共のインスタンスが返却されてしまう。

### 原因
区別する項目がないため

### 修正案
modalityを限定するなどはどうか。

**Comment by HERMITRION** [comment]
ImagingStudyリソースの話と思いますが、DICOMを取り扱うリソースであり、実態はDICOMそのものです。modalityはstudyの部分とseriesの両者にあり、DICOMではstudyには複数のmodalityが入る（シリーズごとに異なるmodalityが存在する可能性がある）ことが想定されており、DICOMではstudyのmodality項目については任意のタグになっています。一方でseriesのタグは一意で必須のため、sesriesのmodalityを見ると区別できます。
これは例えばX線透視下に内視鏡検査を行うなどエックス線検査と内視鏡検査両者の画像が出てくる可能性があるためそのように設計されています。実際の現場ではエックス線画像と内視鏡画像が別のDICOMのstudyとして管理されることの方が多いですが、統合管理できる仕組みとして規格上用意されているものになります。

したがって現時点でのFHIRの定義でこれを変更する必然性は乏しいと考えます。
（検索条件でseries modalityで検索する例を入れるのはありかもしれません。）

**Comment by findex-miyakawa** [comment]
承知しました。
今回は明示的な記述をしないということで了解しまいた。
