### ISSUE TITLE
Medication.ingredient.strengthが示す意味の明確化

### ISSUE THREAD

**Issue by tmitanitky** [jami-fhir-jp-wg/jp-core-v1x#567]
### 概要
Medication.ingredient.strengthのdenominatorが何を指すか不明瞭

### 依頼先
SWG5

### 該当ページ
https://jpfhir.jp/fhir/core/1.1.1/StructureDefinition-jp-medication.html

### 期日
特になし

### 要望背景
例えば、
```
{resourceType: Medication,
  ingredient: [
    { item: ヴィーンF 輸液,
      strength: {
         numerator: 500ml
         denominator: 500ml
      },
     { item: ガスター注射液 10mg,
      strength: {
        numerator: 10mg
        denominator: 1ml
      }
  ]
}
```
といったMedicationがあったとして、それを「100ml投与する」というMedicationRequestがあった場合、システムによっては
ヴィーンFは(500ml/500ml) * 100ml= 100ml
ガスターは(10mg/1ml) * 100ml = 1000mg
投与する指示と解釈される余地はないでしょうか。

全体の投与量（MedicationRequest.dosageInstructionで指定）×成分の力価（Medication.ingredient.strengthで比を指定）で成分の投与量が計算されるというのは、ありうる解釈だと思います。

### 修正案
・denominatorは「1回」固定にする（Ratioでは分母の省略はできない）
・ingredient.denominatorは、「（混注する薬剤の）パッケージ量」ではなく、Medicationとして一体となった薬剤の量を示すことを明記する
・（R5以降では）strengthQuantityのみ利用可にする
などが考えられます。

**Comment by tmitanitky** [comment]
https://jpfhir.jp/fhir/core/1.1.1/StructureDefinition-jp-medicationrequest-injection.html#%E6%8A%95%E4%B8%8E%E8%96%AC%E5%89%A4%E6%8A%95%E4%B8%8E%E9%87%8F%E3%81%AE%E8%A8%98%E8%BF%B0%E6%96%B9%E6%B3%95
に、
「ingredient.strength.denominatorには固定値『１回』をMERIT-9を使用して指定する。」
という記述がありました。

MedicationAdministration、MedicationDispenseにも同様の記述があるため、
JP Core Medication Profile 側でも、`ingredient.strength.denominator`の各要素をfixed valueとすることを提案します。

**Comment by skoba** [comment]
力価は割と面倒な表現をとるので、fixed valueにするのもどうかとは思いましたが、ご指摘の通り紛らわしいこともあるので固定でもいいかなと思います。影響のおよぶ範囲が少し心配ですけども。
ご指摘のような間違いもあり得るので、dosageInstructionに投与速度や総投与量を記載するようにはしていましたけども、仕様の読み違い、実装の間違いはあり得るので。

**Comment by skoba** [comment]
SWGでの検討結果、denominatorにfixed valueを加える方向で進めます。
