### ISSUE TITLE
参照するリソースをcontained属性として内包させる場合のconstraints

### ISSUE THREAD

**Issue by tmitanitky** [jami-fhir-jp-wg/jp-core-v1x#568]
### 概要
「参照するリソースが内包されていること」というルールが実装ガイドに文章として記述されている箇所について、constraintsで記述するようにして、機械的なvalidationを可能にする。

### 依頼先
SWG1

### 該当ページ
https://github.com/jami-fhir-jp-wg/jp-core-v1x/blob/develop/input/fsh/profiles/JP_MedicationRequest.fsh
など

### 期日
特になし

### 要望背景
参照するリソースが内包されていること、というルールが実装ガイドに文章として記述されており、もしリソースがルールに違反する外部リソースを参照していても自動的には検証できない。

https://hl7.org/fhir/R4/references.html
このConstraintsを見ると、containedリソースであることは、`reference.startsWith('#')`というExpressionで表現可能と思われる。

### 修正案
例えばMedicationRequest Injectionプロファイル
https://github.com/jami-fhir-jp-wg/jp-core-v1x/blob/develop/input/fsh/profiles/JP_MedicationRequest.fsh
であれば、

330行目以降に下記を挿入としてはどうでしょうか。
```
Invariant: jp-core-xxx
Description: "MedicationRequest.medicationReference should reference only contained resources."
Severity: #error
Expression: "medicationReference.reference.startsWith('#')"
```
もしくは、
```
* medicationReference^constraint[0].key = "jp-core-xxx"
* medicationReference^constraint[0].severity = #error
* medicationReference ^constraint[0].human = "MedicationRequest.medicationReference should reference only contained resources."
* medicationReference^constraint[0].expression = "medicationReference.reference.startsWith('#')"
```
constraintsの記法は、
https://build.fhir.org/ig/HL7/fhir-shorthand/reference.html#defining-invariants
を参照しましたが、いくつか記法があるようで、上記で良いか検討お願いできますか。

**Comment by skoba** [comment]
現状は外部参照を許可しています。内部参照のみだと実装しづらいという意見や、既にある実装では対応していないという意見があったと記憶しています。
Medicationを参照する形式としているのは注射の場合、JP_MedicationRequest_Injectionですが、内服ではMedicationを参照していません。注射の場合にそうした意見を付与するということでもよろしいｄせほうか？
実装にかかわるところなので慎重にしたいところでもあります。
制約の強化は実装を容易にすることもあれば難しくすることもあります。
スキーマの変更で現行実装に影響を与えるので、取り入れるとしても1.2以降となるでしょう。

**Comment by tmitanitky** [comment]
https://jpfhir.jp/fhir/core/1.1.1/StructureDefinition-jp-medicationrequest-injection.html#%E5%BF%85%E9%A0%88%E8%A6%81%E7%B4%A0
の、
> medicationReference : 医薬品の識別情報は必須でありmedicationReference.referenceが必ず存在しなければならない、JP Coreでは注射の医薬品情報は単一薬剤の場合も Medicationリソースとして記述し、MedicationRequest.contained属性に内包しmedicationCodeableConceptは使用しない

という部分から、外部参照は許可せず、必ずcontainedに内包する方針と誤解していました。

案1:「medicationReference : 医薬品の識別情報は必須でありmedicationReference.referenceが必ず存在しなければならない、JP Coreでは注射の医薬品情報は単一薬剤の場合も Medicationリソースとして記述し、medicationCodeableConceptは使用しない。参照するMedicationリソースは、外部参照としてもMedicationRequest.contained属性に内包しても良い。」

案2:「medicationReference : 医薬品の識別情報は必須でありmedicationReference.referenceが必ず存在しなければならない、JP Coreでは注射の医薬品情報は単一薬剤の場合も Medicationリソースとして記述し、medicationCodeableConceptは使用しない。参照するMedicationリソースは、MedicationRequest.contained属性に内包することが望ましいが、外部参照としても良い。」

などと変更するのはどうでしょうか。medicationDispense、medicationAdministrationにも同様の記述があります。

**Comment by skoba** [comment]
わかりやすさでいうと案1かなぁ。
スキーマ定義体と文書に食い違いがある場合は、影響のおよぶ範囲を考慮しながら文書の方を直す方が多いです。
1.2でアップデートするかどうか、SWGと全体会議で検討します。

**Comment by skoba** [comment]
SWGでの検討の結果、文書について案2をもとに反映させる方向で進めます。

**Comment by tmitanitky** [comment]
検討ありがとうございます。よろしくお願いします。
