### ISSUE TITLE
OID廃止

### ISSUE THREAD

**Issue by yaju123** [jami-fhir-jp-wg/jp-core-v1x#570]
### 概要
OIDは積極的に利用せずURI利用の推奨

### 依頼先
各SWG

### 期日
なし

### 要望背景
OIDには後方互換のメリットがあったりしますが
URIがよりパワフルな表現手法であると思われます

具体的に以下のメリットがあります
・web準拠
　 - semanticな情報交換の要件を満たせる
　- webであることの強力さ
・理解しやすさ
　 - URIの文字列は人間にとって意味が含まれておりわかりやすい
　 - URIの文字列から意味が理解できない場合でも
　　リンク先で定義を紐づけることができるので理解が容易

jp-core利用者の多くはprofileを参照することもないライトユーザです
OIDもURIも意味を指し示すポインタとしての機能に差はありませんが
利用者へのわかりやすさの提供と その積み重ねが重要であると考えます

### 修正案
短中期的にOID/URI 併記の許可
今後のsystemは積極的にURIを採用する
など

具体例：
urn:oid:1.2.392.100495.20.3.51.11312345670　
　　↓
http://jpfhir.jp/fhir/core/identifier/organzation/1312345670/patient
※なお、systemが動的であることには議論があります

**Comment by findex-miyakawa** [comment]
JP Coreでも議論がされ、将来的な置き換えを検討しています。

現状下位互換性を保つために、OIDを主としていますが、別途NamingSystemにてurlベースのものを許容する方向で記載しています。
v2.0のバージョンアップ時の検討課題の一つなっています。

**Comment by skoba** [comment]
同じTerminologyに複数のoidが割り振られている例もみられますし、どこがterminologyの発行元かメンテナンスができているのかとかも☑必要ですね。

**Comment by findex-miyakawa** [comment]
v1.2.0にてURL表記ベースに変更しました。
