### ISSUE TITLE
JP_DiagnosticReportCategory_VSのLOINCのリンク不具合

### ISSUE THREAD

**Issue by ishihara-jp** [jami-fhir-jp-wg/jp-core-v1x#573]
### 概要
[JP_DiagnosticReportCategory_VS](https://jpfhir.jp/fhir/core/1.1.2/ValueSet-jp-diagnosticreportcategory-vs.html) の LOINCコードの外部参照リンク先が存在しない。

### 依頼先
宮川さん？ 平山さん？

### 該当ページ

[JP_DiagnosticReportCategory_VS](https://jpfhir.jp/fhir/core/1.1.2/ValueSet-jp-diagnosticreportcategory-vs.html)

例えば、LP29684-5 (放射線) だと･･･
- 上記ページ記載の外部リンク：http://loinc.org.html/#us-loinc-cs-LP29684-5
- 実際のLOINCの公開リンク：http://loinc.org/LP29684-5

### 修正しないとどう困るか

実装ガイド読者が困りそう

### 原因

どこでURLに **`.html/#us-loinc-cs-`** が混入するのか下記のFSHファイルを見る限りは分かりませんでした。

- https://github.com/jami-fhir-jp-wg/jp-core-v1x/blob/develop/input/fsh/terminologies/JP_DiagnosticReportCategory_VS.fsh
- https://github.com/jami-fhir-jp-wg/jp-core-v1x/blob/develop/input/fsh/aliases.fsh

何か対策方法があれば、教えて頂けると助かります。

**Comment by findex-miyakawa** [comment]
検索をするとus-loinc-csという文字が使われているのは、terminologyserverに格納されている下記のファイルのidに記述がある模様。回避方法はまだわかっていないです。

.fhir\packages\jpfhir-terminology#1.1.1\package\CodeSystem-us-loinc-cs.json
 "id": "us-loinc-cs",

**Comment by findex-miyakawa** [comment]
おそらくv1.1.2リリース時に、loincの参照があっていせずに、一時的にloincを設定していたために起きたものと思われます。
すでに解消されており、最新のビルド環境では解決しています。
https://jpfhir.jp/fhir/core/1.2.0-dev/ValueSet-jp-diagnosticreportcategory-vs.html
