### ISSUE TITLE
病名 検索パラメータ記載誤り

### ISSUE THREAD

**Issue by yaju123** [jami-fhir-jp-wg/jp-core-v1x#578]
### 概要
・検索パラメータとしてはverification-statusが正しいが verificationstatusと記載されている箇所が多数
　clinicalstatusについても同様
・clinical-status,verification-status,categoryの型はtokenが正しい

### 依頼先
SWG4(?)

### 該当ページ
verificationstatus,clinicalstatus
https://jpfhir.jp/fhir/core/1.1.2/StructureDefinition-jp-condition.html#%E5%88%A9%E7%94%A8%E6%96%B9%E6%B3%95

### 修正案
https://hl7.org/fhir/R4/condition.html#search

**Comment by findex-miyakawa** [comment]
AllergyIntroleranceも間違っていたためあわせて修正
