### ISSUE TITLE
不具合発見時の報告導線

### ISSUE THREAD

**Issue by yaju123** [jami-fhir-jp-wg/jp-core-v1x#580]
### 概要
コミュニティに参加していない一般利用者が不具合を発見したときの報告先がわからない

### 依頼先
不明

### 要望背景
Jp-coreを参照するにあたり大小様々な問題を発見することがありましたが
報告先がわからず 結局そのまま忘れ去ってしまうことが往々にしてありました
問題報告がオープンであることが伝われば良いと思います

### 修正案
US Coreではページの最下部に「Propose a change」のリンクが提供されていて
問題点の登録先の誘導がありました。これがわかりやすいかはさておき。
https://build.fhir.org/ig/HL7/US-Core/

**Comment by findex-miyakawa** [comment]
ご指摘ありがとうございます。
JP Coreのホームページにも不具合報告を誘導できるように検討します。

**Comment by skoba** [comment]
Contribution guideを作っていく必要がありますね。
https://docs.github.com/ja/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by findex-miyakawa** [comment]
JP CoreのFooter部分に、質問や指摘を受け付けるリンクを作成しました。
