### ISSUE TITLE
JSONやXMLファイルの改行の折り返しが効かない

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#581]
### 概要
JSONやXMLファイルの改行の折り返しが聞かなくなった。
今までは、CSSにて改行になるように指定していたが、ig-publisherがhtmlの要素に直接text-wrap=nowrapを指定してしまい、コントロールが効かなくなった。

### 該当ページ
リソースやExamlpleのjsonタブで表示されるページ全般

### 修正しないとどう困るか
説明用のhtmlなど、長い１行の存在が分かりにくくなる。

### 原因
ig-publisherがhtmlの要素に直接text-wrap=nowrapを指定してしまい、コントロールが効かなくなった。

### 修正案
案１）現状修正案は見つからない。ig-publisherの修正待ち。
本家のig-publisherにissueを記載する

案２）
強引にig-publisherをforkして修正する（非推奨）

**Comment by skoba** [comment]
案1でしょうかねぇ。宮川さん、issueあげますか？

**Comment by findex-miyakawa** [comment]
v1.2では対処できないので、いったんクローズとします
