### ISSUE TITLE
Medication関連の$everything操作についてOperationDefinionの定義がされていない

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#592]
### 概要
FHIRで定義済みのOperationDefinitionの関する操作は以下のものであり、
Medication関連の-notesで記載している内容にマッチしていない

[base]/Encounter/[id]/$everything
[base]/Group/[id]/$everything
[base]/MedicinalProduct/$everything | [base]/MedicinalProduct/[id]/$everything
[base]/Patient/$everything | [base]/Patient/[id]/$everything

R4定義済みOperation一覧
https://hl7.org/fhir/R4/operationdefinition.html#defined

### 該当ページ
Medication全般

### 修正しないとどう困るか
記述と定義が一致しない。

**Comment by findex-miyakawa** [comment]
https://www.hl7.org/fhir/R4/operation-patient-everything.json.html

を参考にOperationを作成する必要があると考えます。

**Comment by findex-miyakawa** [comment]
slackで本来必要のない操作という結論だったと思います。
mdファイルの記述を削除をお願いできないでしょうか？

**Comment by skoba** [comment]
コメントの整理は完了したと思います。
