### ISSUE TITLE
Invalid Search parameter fhirpath expressions

### ISSUE THREAD

**Issue by brianpos** [jami-fhir-jp-wg/jp-core-v1x#613]
### 概要 _(Overview)_
There are several search parameters in this IG that have invalid fhirpath expressions
(found using the uploadfig IG tester while trying to load into a test server)

### 該当ページ _(Applicable pages)_
search parameter pages:
almost all, though these will not return anything:
http://jpfhir.jp/fhir/core/SearchParameter/JP_Organization_InsuranceOrganizationCategory_SP: Organization - jp-insurance-organizationcategory
http://jpfhir.jp/fhir/core/SearchParameter/JP_Organization_InsuranceOrganizationNo_SP: Organization - jp-insurance-organizationno
http://jpfhir.jp/fhir/core/SearchParameter/JP_Organization_PrefectureNo_SP: Organization - jp-prefectureno

### 修正しないとどう困るか _(impact of not fixing)_
Servers will not be able index and respond using the parameters as expected.

### 原因 _(cause)_
Invalid fhirpath expressions.
* Organization - jp-insurance-organizationcategory
* jp-insurance-organizationno
* jp-prefectureno

### 修正案 _(proposed fix)_
_I'm happy to create a PR to resolve these fhirpath issues if you like._
The other search parameters use the `as()` function that does not work with collections. Switching to `ofType()` resolves that issue.

#### Organization - jp-insurance-organizationcategory
``` fhirpath
Organization.extension.where(url='http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Organization_InsuranceOrganizationCategory').value.as(code)
```
Please change to (have updated to shortcut form too)
``` fhirpath
Organization.extension('http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Organization_InsuranceOrganizationCategory').value.ofType(Coding)
```
> **Note:** that I've only constrained down to the coding type (even though not required as the extension is only of type coding), and not walked into the code property within the coding as the token type search parameters happily work on these.

#### jp-insurance-organizationno
``` fhirpath
Organization.extension.where(url='http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Organization_InsuranceOrganizationNo').value.as(code)
```
The extension referenced here is of type `Identifier`, so the casting to `code` isn't valid. Removing the cast from the end is value as the Token type search parameter can work with the identifier type (that the extension defines)
change to:
``` fhirpath
Organization.extension('http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Organization_InsuranceOrganizationNo').value
```
Also, I'm curious why the identifier is in an extension here rather than in the actual organization.identifiers collection.

#### jp-prefectureno
``` fhirpath
Organization.extension.where(url='http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Organization_PrefectureNo').value.as(code)
```
change to: (as the extension value type is a `Coding`, not `code`)
``` fhirpath
Organization.extension.where(url='http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Organization_PrefectureNo').value
```

**Comment by brianpos** [comment]
https://github.com/brianpos/jp-core-v1x/commit/7d200b15c00f26730a020989550cb80bffd886cd

**Comment by findex-miyakawa** [comment]
dear @brianpos 
Thank you for pointing out these crucial FHIRPath expression errors in our search parameters. We appreciate you taking the time to identify these issues and provide detailed proposed fixes. Your analysis of the as() function issue and the suggested use of ofType() is very helpful. Your issue is valid, and we appreciate you bringing this to our attention.
We would be very grateful if you could create a Pull Request with your proposed fixes.
