### ISSUE TITLE
薬剤に量指定に関する制約エラー

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#625]
### 概要
薬剤にて以下の警告が発生している。

Numerator and denominator SHALL both be present, or both are absent. If both are absent, there SHALL be some extension present
: (numerator.empty() xor denominator.exists()) and (numerator.exists() or extension.exists())

### 要望背景
igpublisherにバージョンアップにより、エラーとして出力されるようになった。

**Comment by findex-miyakawa** [comment]
回の指定がなくなり、デグレードしている様子。

**Comment by skoba** [comment]
制約として 分母の回の指定を固定値にして、exampleに分母書いているとローカル環境でエラーが出ているので消したらデグレードしましたね。

**Comment by findex-miyakawa** [comment]
確認ありがとうございます。
medicationのfshの記述が悪く、merit9のsystem値にCodeSystem→ValueSetを指定していたので、エラーになっていたと思います。
その点についてはすでに修正しました。
