### ISSUE TITLE
JP_ObservationElectrocardiogramInterpretationCode_VSが指定するCodeSystemは存在するのか

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#658]
### 概要
ValueSetからのCodeSystemに対してOIDベースのURLが指定されているが、Terminologyのパッケージに存在していない。
追加する予定はあるのでしょうか？

![image](https://github.com/user-attachments/assets/050d5bdf-a6ee-418f-8f5f-fc257b0507c0)

![image](https://github.com/user-attachments/assets/d1853093-8621-4574-9b7c-c7d3c19fba99)

**Comment by findex-miyakawa** [comment]
コード体系一覧は下記で公開されている？
https://www.j-circ.or.jp/itdata/shindenzu.xlsx

実際に使わているコード、名称の組み合わせは公開されていないのですかね。

**Comment by skoba** [comment]
各コード体系の一覧は公開はされていないようです。各社に問い合わせて中身をいただくことはできるとは思いますが、公開についての同意をえるには時間がかかりそうです。

**Comment by findex-miyakawa** [comment]
現状CodeSystemがない状況のため機械可読のシステムとしてはエラートなってしまします。

https://jpfhir.jp/fhir/clins/igv1/StructureDefinition-JP-Condition-eCS.html
にあるようにSlicingにてsystemだけを指定して、コードはお任せするのはどうでしょうか？

**Comment by skoba** [comment]
ちょっとモデル自体に見直しが入ったので修正遅れます。
