### ISSUE TITLE
ServiceRequect_Common.instantiatesUriの多重度について

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#659]
![image](https://github.com/user-attachments/assets/2870ef3d-52e7-4350-8d69-9d169598447b)

多重度1以上だとValidatorが対応していないとのこと。
多重度設定を少なくすることでエラーが解消するかどうかは要確認

**Comment by findex-miyakawa** [comment]
多重度を0..1にしたら挙動が変わるか確認する

**Comment by qiitarow** [comment]
作業を始めました。重複しましたらすみません。

**Comment by qiitarow** [comment]
修正確認しました。遅れましてすみません。

**Comment by findex-miyakawa** [comment]
確認ありがとうございました。
