### ISSUE TITLE
プログラムを日本語モードで実行したい

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#666]
### 概要
現在のGitActionは英語のモードで動作しているが、これを日本語モードで起動したい。
Validatorの引数にlangの指定があるため、IGPublisherの設定で対応できる可能性がある。

**Comment by sei-matsumoto** [comment]
FHIR公式バリデーターにはterminologyリソースのバリデーション時にdesignationを指定する意味あいのlanguageパラメータが存在します。
https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-LanguagerelatedParameters

一方でIGPublisherの下記ドキュメントを一通り眺めた上で `language` `locale` `designation` 等で検索しましたが該当する操作を発見するには至っておりません。

- [IG Publisher Documentation](https://confluence.hl7.org/display/FHIR/IG+Publisher+Documentation)
- [IG Publisher CLI](https://confluence.hl7.org/display/FHIR/IG+Publisher+CLI)
- [Implementation Guide Parameters](https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters)
ig.iniに記載できる可能性があるため追いかけてみたところ
http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
に行き当たり、こちらの `i18n-default-lang` をjaにして試す価値があるかもしれません。
※ただし肝心のCLIでは出てこないパラメータであるため効果なしの可能性は高いです。
- https://github.com/HL7/fhir-ig-publisher/blob/master/documentation.md
※おそらくメンテされていない

標準が英語であることからは逃れられない可能性が高いかもしれませぬ。

**Comment by findex-miyakawa** [comment]
javaの起動引数に下記を加えることで対応できそうです。
 -Duser.language=ja -Duser.country=JP

**Comment by findex-miyakawa** [comment]
HOT9等は日本語指定をされているので、こちらのほうが正しい警告が出力されるのではと思っています。

**Comment by findex-miyakawa** [comment]
developにマージしました。
