### ISSUE TITLE
JP_MedicationRequestDosageInstructionLine_CSが見つからないエラーとなる

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#675]
### 概要
Terminology  Packageに登録されているが、JP_MedicationRequestDosageInstructionLine_CSが見つからないというエラーがでてしまう

### 該当ページ
![image](https://github.com/user-attachments/assets/8369403d-0a2d-477e-bde2-7fba5f2d2435)

### 修正しないとどう困るか
リンクをたどると、CodeSystemが見えていない

### 原因
不明。symbolic linkが生成されていないのが怪しい？

**Comment by findex-miyakawa** [comment]
@yoshinori-kodama @skoba 
もし情報があればご教示ください。

**Comment by skoba** [comment]
11月6日夜から(en)の用語が見つからないという表示がたくさんでるようになりました。

**Comment by findex-miyakawa** [comment]
環境はUnixでしょうか。
_genonce.sh
の起動引数に日本語指定を入れるように修正するのでお待ちください。

**Comment by findex-miyakawa** [comment]
developにupしましたので、こちらで確認してください。
うまく動かなかったらごめんなさい。

**Comment by findex-miyakawa** [comment]
.fhirフォルダにterminology packegeの中にあるのだが、うまく有効にならない模様。
１回調べたがダメでした。

**Comment by skoba** [comment]
WSL2上のUbuntu 24.04LTSです。今compile中。

**Comment by skoba** [comment]
Warningが少し変わって、tx.fhir.orgに該当Terminologyがないって出てきますね。

A definition for CodeSystem 'http://jpfhir.jp/fhir/Examples/CodeSystem/JP_MedicationRequestDosageInstructionLine_CS' could not be found, so the code cannot be validated (from [http://tx.fhir.org/r4)](file://///wsl.localhost/Ubuntu/home/skoba/src/jp-core-v1x/output/qa-txservers.html#http://tx.fhir.org/r4)

**Comment by findex-miyakawa** [comment]
/home/runner/.fhir/packages/jpfhir-terminology#1.2.1/package/
配下にあるので、本来は見えるはずなのですが。

**Comment by findex-miyakawa** [comment]
tx.fhir.orgには見に行かない設定 （javaの起動引数 「-tx na」を指定）になっています。
なぜこのCodeSystemだけが見えないのかわからない。

**Comment by skoba** [comment]
$JP_MedicationExampleLine_CSを示している先のCodesetが確かにないです。VSはあるんですけども。どっかで消えてる。

**Comment by skoba** [comment]
ここで消えたみたいです。
https://github.com/jami-fhir-jp-wg/jp-core-v1x/commit/7e0bbf315a31a51d8d6ac87f1015251bfd71d5a1

**Comment by findex-miyakawa** [comment]
JP Coreで定義していても同様のエラーが出ていました。
.fhir\packages\jpfhir-terminology#1.2.1\package\CodeSystem-jp-medication-example-line-cs.json

にファイルがあり、重複するためJP Coreを消しました。
ただこちらがうまく反映しないです。
