### ISSUE TITLE
医療機関コードの整理

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#693]
### コード体系
医療機関コード＝保健医療機関コード、保険医療機関以外のコード、その他混合
system値として、CLINSにも使われている医療機関コードのURIに変更してもよいか

**Comment by skoba** [comment]
先頭2桁が都道府県番号、次の1桁が点数表番号（医科1，歯科3、調剤4）、その次の7桁が医療機関に割り当てられたコードで、東大医療情報部のサイトにもその旨があるので、11桁というのがどこから来ているのかがわからない。
https://www.m.u-tokyo.ac.jp/medinfo/qrs/organization-code.pdf

**Comment by skoba** [comment]
保険医療機関コードは厚生労働省の地方厚生局でとりまとめていて、全体を統括したマスタは存在していないという話を以前に聞いたことがあります。Issuerが地方厚生局なのか厚生労働省本省とするのかもややこしいので、URIをわけるかどうかも難しいと思う。

**Comment by skoba** [comment]
保険医療機関コード以外の医療機関コードとしては、文部科学省大学附属病院施設区分、ORCAに登録する医療機関コードなどがあります。

**Comment by findex-miyakawa** [comment]
![image](https://github.com/user-attachments/assets/14e9b486-da52-48c4-8e53-45c09cbf691e)
の表記があり、勘違いしました。
"1"+ 医療機関番号でした。
この表現も１１桁とせずに、"1"+医療機関番号10桁としたほうが分かり易いです。
