### ISSUE TITLE
Observation_Endoscopy.value[x]の取り扱いについて

### ISSUE THREAD

**Issue by findex-miyakawa** [jami-fhir-jp-wg/jp-core-v1x#716]
### 概要
CodableConcept形にtext型があるため、Codeを入れずにTextだけをいれる方法もあるため、String型を定義しなくてもよいと思われる。

どうしても両方を定義する場合は、
 #715
のようにそれぞれの型について定義をするべきと考える。

CodableConceptとStringの混在としているが、バインディングがStringに対してもかかっているとのIGPublisherの警告がきっかけ。

**Comment by Takashi-Ozaki-Olympus** [comment]
コメントありがとうございます。

どれか一つに限定しないとIG Publisherの警告がでるとのことですので、CodableConceptのみに修正頂けますでしょうか？

お手数をお掛けしますがよろしくお願いいたします。
[JP_Observation_Endoscopy.zip](https://github.com/user-attachments/files/17895423/JP_Observation_Endoscopy.zip)

**Comment by findex-miyakawa** [comment]
ファイルが古いようです。

**Comment by findex-miyakawa** [comment]
修正しました。ありがとうございました。
