### ISSUE TITLE
swg1 - 「:exact」指定における異体字の扱い

### ISSUE THREAD

**Issue by m-nakagawa** [jami-fhir-jp-wg/jp-core-v1x#81]
### 概要

日本語の文字列検索では「:exact」を指定された場合でも異体字を同一視するように定める。

### 依頼先

SWG1

### 該当ページ

https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/guide-stringSearch.html

### 期日

Milestone 1.1対応

### 要望背景

デフォルトのstring検索は"先頭一致"であり、たとえば「Patient?name=森」を検索すると「森田」にも一致してしまう。

ところが、"全体一致"を指定する「:exact」は同時に"厳密一致"（大文字小文字やアクセント記号を区別する）の指定の意味を持たせられている。
"厳密一致"では異体字を区別すべきと解釈できるので、異体字を区別しないとすることを提案する。。実用上は異体字を区別しない検索の方が求められると思われるからである。
同様の理由で、異体字だけでなく半角・全角の同一視、「ブ」と「ヴ」や促音の扱いも「:excat」の対象外とするほうが良いと思われる。

他に"全体一致"を指定する手段としては_filterでeq演算子を使う方法がある。（「:exact」で異体字を区別するとし、全体一致での文字列検索では_filterの使用を推奨する方法もありうるか？）

「:exact」で異体字を区別しないことを定める短所としては、異体字を区別する検索が行えないことがある。

[参考資料「人名のサーチパラメータ定義.pptx」](https://hl7fhir-jp-wg.slack.com/archives/CM0CHU6G7/p1655104052230149)

### 修正案

日本語の文字列検索では「:exactを指定された場合であっても異体字、全角・半角文字などを
同一視する」という記述を加える。

**Comment by tmitanitky** [comment]
`:exact`のところで、

> Note that the handling of (extended) [grapheme clusters ](http://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries) is within the discretion of the server, i.e. the server decides if a string search parameter matches on `canonically equivalent` characters, or matches on the actual used Unicode code points.

とありますが、この例示は「正準等価」であれば同一視して異体字を区別しないこと（また、反対にユニコードのコードポイントが一致するもののみを同一視すること）も、exactの範囲内であることを示しています。ユニコードにおける漢字の取り扱いの議論で、異体字は本来正準等価ではなく、互換等価であるべき、という議論もあるようですが…。また、全角⇔半角は正準等価よりもやや広い概念である互換等価です。

現時点で通常のstring検索においても、
> サーバーは検索のときに、丸付き文字（①⇔1）、数字（2⇔Ⅱ⇔II⇔二）、ひらがな⇔カタカナ、[カタカナの正規化](https://www.scripts-lab.co.jp/mindsearch/mindsearchHypermanual/modectrl.html)（末尾の長音記号の削除、ベ⇔ヴェなど）、[新字体⇔旧字体](https://www.asahi-net.or.jp/~ax2s-kmtn/ref/old_chara.html)、統合漢字⇔互換漢字、異体字セレクタの処理、[住所の正規化](https://info.gbiz.go.jp/tools/imi_tools/index.html)、[病名の正規化](http://sociocom.jp/~data/2018-manbyo/index.html)など、必要性に応じて自由に追加の正規化を行うことができる（MAY)

となっており、異体字の同一視を求めていません。これは、何が異体字で何が異なる字なのか定義が難しい（旧字体は？）という点と、定義次第では実装が煩雑になりうること、「福」と「福」や、「斉」と「斎」と「齋」と「齊」などを区別したいというニーズや逆に区別したくないというニーズがあるかもしれないこと、などが理由だったと思います。

したがって、`:exact`について変更するのであれば、通常のstring検索から変更する必要があると思います。

（これを見ていて気付きましたが、通常のstring検索において「アクセントやダイアクリティカルマークの無視」をするので、濁点・半濁点を無視しないといけないですね。）

**Comment by findex-miyakawa** [comment]
アクセントやダイアクリティカルマークの無視については、別Issueを立てていただき、既に対応をいたしました。
本件、v1.1と恒久対策の２つの観点で落としどころを探したいところですが、どのようなやり方がありますでしょうか？

1)人名のみexact検索時の異字検索ルールを変更する
2)すべて検索項目について異字検索ルールを変更する
3)exact検索時は、異字体を検索しない
　→　検索する側が異字体を考慮して検索する
4)人名の検索時は部分一致検索ではなく、全体一致とする。
　→ containsでも同じ問題が発生しますが。
5)異字体を含むか含まないかを制御するパラメータを用意する。
　※手段はわかっていませんが・・。

あたりでしょうか。

**Comment by tmitanitky** [comment]
例えば福の新字・旧字については下記のコードポイントがあります。

福(U+798F、統合文字）
福(U+FA1B、互換文字）
福(U+798F U+FE00、統合文字＋異体字セレクタ)

「同じ見た目の異体字は同一視するが、見た目が異なる異体字は分ける」という日本語話者にとって比較的自然な処理を実装するためには、「異体字セレクタを削除する」とか、「統合文字と互換文字については正規化を行わない」といった対処だけでは難しく、「U+798F U+FE00は、U+FA1Bに一致する」という対応表を多くの漢字について持つ必要があります（既存の表があるかどうかは分かりませんが、無さそうな気がします。)

アップルは統合漢字と互換漢字を分けるために、恐らく「漢字については正規化せずにコードポイントが等しいかどうかで検索する」という方針じゃないかと思いますが、異体字セレクタがついている場合の「福」と「福」の違いには多少目をつぶって「異体字セレクタは削除した上で、統合漢字と互換漢字は分けて検索する」という方針もアリでしょう。一方で「全て互換漢字も統合漢字へ正規化して検索する」という方針もあり得ます。

異体字セレクタを含んだ漢字の検索について、調べた限りではコレというゴールドスタンダードな方法がないようなので、JP CoreでSHOULDとして規定するのは難しいように思います。あるとすれば、（ノーマルなstring検索もあわせて）「追加の正規化を行うことが望ましい（MAY)」といったやや強めの文言への変更かと思いますがいかがでしょうか。

> 全体一致
`string`では「正規化＋先頭一致」、`:exact`では「厳密＋全体一致」で、「正規化＋全体一致」の検索ができないという問題については、実際にどのようなユースケースを想定されていますか？familyやgivenでソートすれば全体一致のものが先に出てくるはずなので、結果を目視する用途ではおおむねそれで問題ない（例外規定を設ける負担が上回る）ようにも思います。

**Comment by m-nakagawa** [comment]
確かに異体字の処理方法を指定することは難しいと思います。異体字の同一視を規定する場合には「string検索でモディファイア:exactが指定されたときでも（実装法を問わず）異体字を同一視しても構わない」ということだけでよいのではないでしょうか。

>  stringでは「正規化＋先頭一致」、:exactでは「厳密＋全体一致」で、「正規化＋全体一致」の検索ができないという問題については、実際にどのようなユースケースを想定されていますか？familyやgivenでソートすれば全体一致のものが先に出てくるはずなので、結果を目視する用途ではおおむねそれで問題ない（例外規定を設ける負担が上回る）ようにも思います。

たとえば
『「森」と「森田」を区別するために:exactを使うと「高橋」の検索から「髙橋」が漏れるので、:exactを使わずに、ソートした候補を目視で確認するなどクライアント側で絞り込むような設計とする。』
のような実装ガイドを提供するようなイメージでしょうか。

異体字のほかに、濁点・半濁点などの扱いも:exactで切り替えることが必要なケースもありそうですね。

6)全体一致を指定するときには_filterを使う。ex:「_filter=family eq "森"」

という方法もあるので、:exactに厳密一致の意味を残しておく価値はあるかもしれません。[_filter](http://hl7.org/fhir/search_filter.html)の記述ではcase-insensitiveとあるので、正規化した結果で比較すると解釈してよいのではないかと思います。（厳密には、アクセントなどの記号の扱いなどについては書かれていません。）

**Comment by m-nakagawa** [comment]
サーバの実装ガイドとしては、[2.5.1文字列検索](https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/guide-stringSearch.html#%E6%96%87%E5%AD%97%E5%88%97%E6%A4%9C%E7%B4%A2)に_filterに関する記述を追加する必要があると思います。ただ_filterは成熟度が高くなく記述も厳密ではないので言及の仕方が課題かもしれません。

クライアントの実装ガイドとして仕様の理由や想定する使い方を書く章があるとよいと思いますがいかがでしょうか。
たとえば先頭一致の結果を目視するような実装は、医療機関でない方がユーザのときに他の人名がみえていいのかといった観点もあるかと思います。今はそうした詳細まで踏み込む余裕はないかもしれませんので、今後そうした情報を掲載する先を予約しておくだけでもいいかもしれません。

**Comment by tmitanitky** [comment]
案です。「正準等価」の例はあくまで英語圏だからそう書いてあるだけで、そのまま日本に持ち込むのはおかしいとも思い直しました。「互換漢字と統合漢字は正規化しない」をMAYとして記載しています。SHOULDにするか少し迷いましたがいかがでしょうか。

「1. case sensitiveな完全一致
 - string: exact
 - token (～)
FHIR R4において、「caseや発音区別符号を含めた完全一致」として定義されている。ただし、発音区別符号に伴う合成文字など正準等価な文字を正規化するか、単純にユニコードのコードポイントによって検索するかはサーバーの実装に委ねられている。一方で、日本語において正準等価性に基づいた正規化を行うと、CJK統合漢字（例：福）とCJK互換漢字（例：福）が正規化されてしまい、:exactというパラメータの趣旨にそぐわないと考えられる。したがって、JP Coreにおいては、CJK統合漢字とCJK互換漢字を区別した完全一致を行うことが望ましい（MAY）と定める。ただし、異体字セレクタについてはコードポイントによる一致のみを検出するか、何らかの対応（例：福(U+798F U+FE00)や福(U+798F U+E0101)、福(U+798F U+E0103)で検索した場合に、福(U+FA1B)をヒットさせる、など）を行うかはサーバーの実装に委ねることとする。」

最初の記載時に_filterのことを見落としていました。記述追加が必要という意見に賛成です。
「大きく５種類に」に変更して、

「5. _filterを用いた検索
通常のsearch parameterについて、_filterパラメータを用いて検索することができる。ただし、Maturity Level:2 であることに注意する。String型のsearch parameterに対しては、
- eq (equals: Character sequence is the same (case insensitive))
- ne
- co (contains: Character sequence matches somewhere (case insensitive))
- sw (starts with: Character sequence matches from first digit (left most, when L->R) (case insensitive))
- ew (ends with: Character sequence matches up to last digit (right most, when L->R) (case insensitive))
- gt / lt / ge / le (Based on Integer comparison of Unicode code points of starting character (trimmed) (case insensitive))
といったオペレータが用意されており、`eq`を用いてcase insensitiveな全体一致をクエリできる。」
を追記することを提案します。

**Comment by tmitanitky** [comment]
通常のテキスト検索部分の修正（先頭一致検索であることの明記）については別issueにしました。
https://github.com/jami-fhir-jp-wg/jp-core-v1x/issues/102
