### ISSUE TITLE
「通常の文字列検索」に濁点・半濁点の処理を追記する

### ISSUE THREAD

**Issue by tmitanitky** [jami-fhir-jp-wg/jp-core-v1x#86]
### 概要
「実装上は、Unicodeの互換正規化（NFKCもしくはNFKD）に、大文字小文字の変換、濁点・半濁点の削除、句読点と連続する空白の処理を加えることで条件を満たすことができる。 」と、「濁点・半濁点の削除、」を挿入する。

### 依頼先
SWG1

### 該当ページ
https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/guide-stringSearch.html

### 要望背景
「実装上は、Unicodeの互換正規化（NFKCもしくはNFKD）に、大文字小文字の変換、句読点と連続する空白の処理を加えることで条件を満たすことができる。 」とあるが、濁点半濁点も発音区別符号であり、その処理を加えなければ、FHIRの条件を満たすことができない。濁点の処理を加えることで、「田端（たばた）」さんを「たはた」「たばた」どちらで検索してもヒットするようになる。

### 修正案
「実装上は、Unicodeの互換正規化（NFKCもしくはNFKD）に、大文字小文字の変換、濁点・半濁点の削除、句読点と連続する空白の処理を加えることで条件を満たすことができる。 」と、「濁点・半濁点の削除、」を挿入する。

**Comment by tmitanitky** [comment]
修正ありがとうございました。

「濁点・半濁点の削除」を加えると、「なお、濁点半濁点の合成文字・結合文字については、発音区別符号の正規化としてFHIR®自体に規定されていると解釈される。」が不要になることに気が付きました。二度手間になってしまい申し訳ありません。

**Comment by findex-miyakawa** [comment]
Pull Requestを作成しました
#103
