### ISSUE TITLE
Patient.name検索でのフルネームの扱い

### ISSUE THREAD

**Issue by m-nakagawa** [jami-fhir-jp-wg/jp-core-v1x#88]
### 概要

Patientのサンプルデータにある名前「山田 太郎」が、
Patient.name検索の例「GET [base]/Patient?name=山田太郎」にヒットしない。

### 依頼先

SWG3

### 該当ページ

https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-patient.html

### 修正しないとどう困るか

データサンプルと検索サンプルに同じ人名（山田太郎）が使われているので、
常識的にはヒットするものとして解釈されてしまい、混乱を招く。

### 原因

データには姓名の間に空白があるが、検索パラメータにはない。

### 修正案

フルネーム検索での利便性を考えると「案3」が良いと思われる。

* 案1. 検索例を「GET [base]/Patient?name=山田太郎」から
「GET [base]/Patient?name=山田%20太郎」へ変更する。
* 案2. サンプルデータを「"text": "山田 太郎"」から「"text": "山田太郎"」へ変更する。

* 案3. 日本名の使われ方に沿った検索方法を定義する。　　
  「name=山田太郎」と「name=山田%20太郎」の両方にヒットするようにする  
  （FHIR仕様では、HumanNameの検索について各地域の文化に合わせよとされている）  
    a. HumanName.textには、HumanName.familyとHumanName.given[]を1文字の空白  
 　　　　で連結した文字列として記述することを定める。
    b. 「HumanNameの検索ではfamilyとgiven[]を空白を入れずに連結した文字列にもヒットさせる。」

[関連項目「HumanName.textの姓名の間に空白 #87」](https://github.com/jami-fhir-jp-wg/jp-core-v1x/issues/87)
[参考資料「人名のサーチパラメータ定義.pptx」](https://hl7fhir-jp-wg.slack.com/archives/CM0CHU6G7/p1655104052230149)

**Comment by tmitanitky** [comment]
3が良さそうに思います。改めて確認すると、「It is at the discretion of the server whether to pre-process names, addresses, and contact details to remove separator characters prior to matching in order to ensure more consistent behavior.」として例示もされていました。
