### ISSUE TITLE
SWG5: JP MedicationStatement Profileの追加

### ISSUE THREAD

**Issue by skoba** [jami-fhir-jp-wg/jp-core-v1x#90]
### 概要
MedicationStatement Resourceに対する日本版Profileの追加

### 依頼先
SWG5

### 該当ページ
https://www.hl7.org/fhir/medicationstatement.html

### 期日

未定

### 要望背景

MedicationStatement ResourceはJAMI標準，退院サマリーと診療情報提供書に使用されており，対応する日本語版Profileが必要。

### 修正案
Profileについて，JAMI標準，退院サマリーに記載されている仕様と合わせて検討が必要。

**Comment by findex-miyakawa** [comment]
v1.2で実現するため、本レポジトリとしてはクローズします。
