### ISSUE TITLE
swg3-Organizationリソースにおける、保険医療機関番号、点数表コード、都道府県番号のIdentifierへの記録

### ISSUE THREAD

**Issue by m-nakagawa** [jami-fhir-jp-wg/jp-core-v1x#91]
### 概要

現在の仕様では、保険医療機関番号、点数表コード、都道府県番号をそれぞれextensionとして
Organizaitionリソースへ直接付加している。

これを、Organization.identifier:MedicalInstitutionCodeヘ付加するように改めることを提案する。

### 依頼先

SWG3

### 該当ページ

https://jami-fhir-jp-wg.github.io/jp-core-v1xpages/jpcore-r4/develop/StructureDefinition-jp-organization.html

### 期日

Milestone 1.1対応

### 要望背景

* 保険医療機関番号、点数表コード、都道府県番号はOrganization.identifier:MedicalInstitutionCodeの構成要素であるため、ここに有効期間などの情報とともに格納することが妥当だと思われる。
* （稀なケースと思われるが）Organizationの番号の有効期間を確認するユースケースに対応できるようになる。

### 修正案

保険医療機関番号、点数表コード、都道府県番号を格納するextensionを、Organizationリソースのトップレベルから、Organization.identifier:MedicalInstitutionCodeの下へ移動する。
これらのextensionに対する検索ユースケースを確認し、不要であればextensionに対するSearchParameterを廃止する。

**Comment by m-nakagawa** [comment]
修正案に、extensionに対するSearchParameterの廃止検討を追加しました。

**Comment by k-danbara** [comment]
Detailed DescriptionsのOrganization.identifier:medicalInstitutionCodeに「都道府県番号＋点数表コード＋保険医療機関番号」の値が格納されることを記載済。
